### ISSUE TITLE
Developer: Cancel Buttons are BROKE

### ISSUE THREAD

**Issue by poofichu** [punchcard-cms/punchcard#113]
_As a_ user _I want_ to be able to cancel a form editing session _so that_ when I change my mind about editing a form, I can move on.

```gherkin
Feature: Working cancel button
  As a user
  I want to be able to click a working cancel button
  So that I can cancel editing a form

  Scenario: a user cancels editing a form
    Given a working cancel button
    When a user wants to cancel editing a form
    Then they can easily click the damn cancel button
```

---

**Comment by ineedsubstance** [comment]
I think this is working now, at least for creating and editing content.

**Comment by scottnath** [comment]
I think that yes...the cancel buttons are doing _something_, but before we close this...can you both please confirm that they are doing what you want?

**Comment by ineedsubstance** [comment]
The only issue I see is when you edit existing content and hit _cancel_, you are directed to the the revisions screen ([example](http://watson-cms.stage1.mybluemix.net/content/api/f82bca2a-ce61-4c01-bb87-e10abbbb2c89/)). This seems a little disorienting, and would suggest redirecting the user back to the content type list ([example](http://watson-cms.stage1.mybluemix.net/content/api)) screen instead.

**Comment by poofichu** [comment]
I made this bug way back before we had any flows in the mix.  Maybe revisit once we get the UX up to par with what flows we want?  The variable you put in for the cancel button to work correctly is related to that....

**Comment by scottnath** [comment]
I see. I'll remove `bug` from this as the links to do _something_ and we'll just plan to rewrite this story to reflect the new paradigm...whenever we know what that is!

**Comment by joshkimmell** [comment]
will revisit if there is an issue with the flow
