### ISSUE TITLE
Developer: Content name is not displaying in content list

### ISSUE THREAD

**Issue by joshkimmell** [punchcard-cms/punchcard#137]
As a content creator, I want to be able to see a list of content by name, so that I know what content to choose to "edit".

**I don't see the names**
![image](https://cloud.githubusercontent.com/assets/8161298/17074265/6570aaa8-503f-11e6-9b7f-3e074a288cfe.png)

**Comment by scottnath** [comment]
@joshkimmell this is being worked on.

There is a story for tracking:
https://github.com/punchcard-cms/punchcard/issues/143

and a PR with some open questions:
https://github.com/punchcard-cms/content-types/pull/72

Once that PR is complete, I'll update Punchcard using the new `key` and that should fix this issue.

**Comment by scottnath** [comment]
This is complete.
