### ISSUE TITLE
Core Developer: Object Recognition

### ISSUE THREAD

**Issue by poofichu** [punchcard-cms/punchcard#177]
```gherkin
Feature: Review Content
  As a content approver
  I will be able to review content
  So that I can either approve or decline the content

  Scenario: Input Type with an Object
    Given that I am reviewing content in the approval flow
     When I see an input type
     And that input type has an object
     Then I will see the input description in the UI

Scenario: Input Type without an Object
    Given that I am reviewing content in the approval flow
     When I see an input type
     And that input type has no object
     Then I will NOT see the input description in the UI
```

----------------

- [ ] Review content / input type with an object
- [ ] Review content / input type without an object

**Comment by joshkimmell** [comment]
@poofichu and josh will rewrite with more specifics
http://localhost/content/api/f82bca2a-ce61-4c01-bb87-e10abbbb2c89/12/approve

**Comment by poofichu** [comment]
@scottnath posting this here so we don't lose it.  This is the technical mumbo jumbo:

- [ ] tell nunjucks to recognize if a variable is an object and if it has anything in it  
- [ ] update approval rending page to use different classes

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/17782550/afdb9b5c-6539-11e6-8e42-76de7a568403.png)

**Comment by joshkimmell** [comment]
@scottnath to write a new story: Solve in 3 different chunks:
1. single piece of content (image, block of text)
2. multiple entries as single object
3. repeated piece of content

make sure that the classes are different

**Comment by scottnath** [comment]
This story has been written: https://github.com/punchcard-cms/punchcard/issues/383
