### ISSUE TITLE
Content Creator: Verify I am logged in

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#217]
_As a_ Content Creator, _I want_ my Account ID (email) to be visible after I log in _so that_ I can verify that I am logged in as me.

```gherkin
Feature: Verify I am logged in
  As a Content Creator,
  I want my Account ID (email) to be visible after I log in
  So that I can verify that I am logged in as me.

  Scenario: Expose my Account ID (email)
    Given that, I am logged into the CMS
      And that I entered my account email to log in
     When I navigate the CMS
     Then I will be able to verify the account that I am logged in as
       And that my Account ID (email) will be visible on every page I navigate to
```

---

**Verify I am logged in:**
- [ ] Expose my Account ID (email)

**Comment by ineedsubstance** [comment]
🎱

**Comment by joshkimmell** [comment]
@ineedsubstance 
what if we just show the username as everything before the @?
so it would be something like... `mperson` where `mperson@this.com` is the full username.

**Comment by ineedsubstance** [comment]
Exploring different layouts for the navigation when adding Account ID, but also trying to think about what the future may hold. There are future stories for adding things like change password, search, notification/alerts, and possibly more things to be added to the navigation to consider.

You may notice that "HOME" was removed from the navigation. It's a pretty common pattern for the logo in the global navigation to link back to the HOME, which Punchcard already does. So having a separate nav item for HOME is redundant. On mobile, I did add a nav item for DASHBOARD, as the header could be used in some cases to expand the mobile menu.

The work also lives in [Box](https://ibm.app.box.com/files/0/f/11055702858/Punchcard) if anyone wants's to view it there.

I started with mobile first and have 7 iterations on the mobile nav, and then moved to desktop where I have 3 versions.

@joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey @Snugug - Looking for feedback.

---

## MOBILE

![punchcard-mobile-v1](https://cloud.githubusercontent.com/assets/3981381/17973646/e31efd1e-6aa8-11e6-915c-736b712e7e93.png)

![punchcard-mobile-v2](https://cloud.githubusercontent.com/assets/3981381/17973650/e8e289dc-6aa8-11e6-9d76-f19eec5ee855.png)

![punchcard-mobile-v3](https://cloud.githubusercontent.com/assets/3981381/17973652/ee0ea13e-6aa8-11e6-914e-e59ae81a33de.png)

![punchcard-mobile-v4](https://cloud.githubusercontent.com/assets/3981381/17973656/f33e08c0-6aa8-11e6-91b3-d8f233069d37.png)

![punchcard-mobile-v5](https://cloud.githubusercontent.com/assets/3981381/17973662/f833f7b8-6aa8-11e6-81d7-bb6fd36810c1.png)

![punchcard-mobile-v6](https://cloud.githubusercontent.com/assets/3981381/17973668/fc52ac36-6aa8-11e6-811c-9045fbf107cb.png)

![punchcard-mobile-v7](https://cloud.githubusercontent.com/assets/3981381/17973680/026071bc-6aa9-11e6-9c62-3bb9bde92d7a.png)

---

## DESKTOP

![punchcard-desktop-v1](https://cloud.githubusercontent.com/assets/3981381/17973695/0d9cee48-6aa9-11e6-9cc3-7bf0c16e21d9.png)

![punchcard-desktop-v2](https://cloud.githubusercontent.com/assets/3981381/17973702/12b21b60-6aa9-11e6-871d-6869fc0ed51a.png)

![punchcard-desktop-v3](https://cloud.githubusercontent.com/assets/3981381/17973707/16e3ca12-6aa9-11e6-8b92-5e635dd0ea3b.png)

**Comment by mkiang3051** [comment]
@ineedsubstance Sweet!!! These look great!
While I do like the look of having the logo center-aligned, I think it's probably more practical to have it left-aligned.
I do think having either a `menu

**Comment by joshkimmell** [comment]
@ineedsubstance: need a new story for a further iteration on this one. Also need a story for @scottnath to do the backend.
