### ISSUE TITLE
Content Creator: identify where I am and navigate with ease

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#219]
_As a_ Content Creator, _I want_ to be able to identify where I am and where I've been in context to the site _so that_ I can easily navigate the CMS and so I can retrace my steps if I need to go back.

```gherkin
Feature: Identify where I am and navigate with ease
  As a Content Creator,
  I want to be able to identify where I am and where I've been in context to the site
  So that I can easily navigate the CMS 
    And so I can retrace my steps if I need to go back.

  Scenario: Provide Location-based breadcrumbs
    Given that, the CMS is complex and has multiple levels of content
       And I may need to retrace my steps when trying to accomplish a task
     When I navigate the CMS
     Then I will get a clear idea of where I am in the website’s hierarchy 
       And a clear indicator of the current page I am on
       And the ability to navigate back one or more levels at any point
```

---

**Identify where I am and navigate with ease:**
- [ ] Provide Location-based breadcrumbs

**Comment by joshkimmell** [comment]
I think this could be its own epic about Navigation.

**Comment by ineedsubstance** [comment]
Done https://github.com/punchcard-cms/punchcard/issues/269

**Comment by ineedsubstance** [comment]
🎱

**Comment by ineedsubstance** [comment]
@joshkimmell @mkiang3051 @poofichu @scottnath - This story is ready to be reviewed

**Comment by joshkimmell** [comment]
🎱

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu @mkiang3051 @scottnath -  Requesting feedback.

---

v1 - Traditional location-based breadcrumbs. On mobile, dashboard/home is an icon to save space and expands out to a text link as the screen get's larger.

![mobile-breadcrumbs-v1](https://cloud.githubusercontent.com/assets/3981381/18065364/344a1f7c-6df9-11e6-8561-44fd6349c0f7.png)

![desktop-breadcrumbs-v1](https://cloud.githubusercontent.com/assets/3981381/18065370/3bfcd174-6df9-11e6-8b2c-b42216a17f20.png)

---

v2- Used a `/` instead of an `>` to show what that might look like and also used the home icon for all size screens. Basically the same as v1 besides those 2 changes.

![mobile-breadcrumbs-v2](https://cloud.githubusercontent.com/assets/3981381/18065402/5cf6aad0-6df9-11e6-8876-d99c84a0be0a.png)

![desktop-breadcrumbs-v2](https://cloud.githubusercontent.com/assets/3981381/18065405/61a4e420-6df9-11e6-9df1-9d1b88c7ffe8.png)

---

v3 - Changing up the link names to reflect what actual content that was selected to get to this point.

![mobile-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18065413/6dc37384-6df9-11e6-84c8-81ef554ad48f.png)

![desktop-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18065421/72a6f920-6df9-11e6-99a4-8cc63f001e22.png)

---

v4 - Another take on being more clear on the path that got the user to this point.

![mobile-breadcrumbs-v4](https://cloud.githubusercontent.com/assets/3981381/18065437/7c675248-6df9-11e6-8dc0-df828476ac0b.png)

![desktop-breadcrumbs-v4](https://cloud.githubusercontent.com/assets/3981381/18065442/7e79aa40-6df9-11e6-84b9-0680c29a9a17.png)

**Comment by joshkimmell** [comment]
@ineedsubstance: closing this as the explorations are done. Let's discuss and write a new story to proceed.
