### ISSUE TITLE
Bug: checkboxes and radios hidden

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#226]
The scss is creating a `display:none` for checkboxes and radio buttons coming from input plugins.
## Steps for Reproducing
- Locally: `npm run dev`
- navigate to a form which should have checkboxes
- see that checkboxes are `display: none`
### see that checkboxes are `display: none`

![screen shot 2016-08-09 at 5 11 08 pm](https://cloud.githubusercontent.com/assets/216931/17533787/582e3130-5e54-11e6-9c4f-487b58f112f0.png)
## Affected Browsers
- [ ] {{Chrome 51 on Mac 10.11}} / {{Production, Development}}
## Runtime Version

Punchcard-CMS 1.11

**Comment by poofichu** [comment]
@scottnath This is happening because `label` needs to come after the checkbox input.

I updated the html for multiple checkbox inputs, but where can I update for a single checkbox?

**Comment by scottnath** [comment]
Morning @poofichu so [this is the html in the current checkbox plugin](https://github.com/punchcard-cms/input-plugin-checkbox/blob/master/index.js#L48)
```
<ul>{% for option in checkbox.options %}<li><input type="{{checkbox.type}}" name="{{checkbox.name}}" id="{{checkbox.id}}--{{loop.index}}" value="{{option.value}}" {% if checkbox.value %}{% if option.value in checkbox.value %}checked{% endif %}{% endif %}><label for="{{checkbox.id}}--{{loop.index}}">{{option.label}}</label></li>{% endfor %}</ul>
```

And [this is the html for boolean](https://github.com/punchcard-cms/input-plugin-boolean/blob/master/index.js#L40):
```
{% for option in boolean.options %}<label for="{{boolean.id}}--{{loop.index}}"><input type="{{boolean.type}}" name="{{boolean.name}}" id="{{boolean.id}}--{{loop.index}}" value="{{option.value}}" {% if option.value in boolean.value %}checked{% endif %}>{{option.label}}</label>{% endfor %}
```

Definitely a difference. Do you have time to create a PR to fix boolean? Are there any changes needed to checkbox as well?

**Comment by poofichu** [comment]
10-4 captain!  I will PR the boolean 👍

**Comment by scottnath** [comment]
@poofichu where are we with this issue?

**Comment by ineedsubstance** [comment]
This looks resolved [here](https://github.com/punchcard-cms/input-plugin-boolean/pull/61) and on the [input-plugin-boolean](https://github.com/punchcard-cms/input-plugin-boolean/pull/61).
