### ISSUE TITLE
Content Creator: Access to all content I'm working on

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#228]
_As a_ Content Creator, _I want_ to be able to access all the content I am working on in one place _so that_ I can find that content quickly and continue to make changes to it.

```gherkin
Feature: Access my latest
  As a Content Creator,
  I want to be able to access all the content I am working on in one place
  So that I can find that content quickly and continue to make changes to it.

  Scenario: Current drafts
    Given that, it may take several passes before a piece of content is ready for the approval workflow
      And that I may be working on multiple items at once
     When I visit the CMS home page
     Then I will see a list of all the drafts I am working
       And be able to edit each draft to continue working on it

  Scenario: Waiting for approval
    Given that, there is an approval workflow
      And that I may have submitted 1 or more items for approval
      And that I may be waiting for feedback on those items
     When I visit the CMS home page
     Then I will see a list of items that I created that are in the approval workflow
       And be able to see the status of the items that are waiting for approval
       And who is assigned to approve that content

  Scenario: My history
    Given that, I touch lots of different content
      And I may want to revisit or reference that content in the future at anytime
     When I visit the CMS home page
     Then I will be able to see a list with my history of the content that I have worked on
       And be able to view all associated revision
       And be able to edit the latest revision
```

---
**Access my latest:**
- [x] Current drafts
- [x] Waiting for approval
- [x] My history

**Comment by ineedsubstance** [comment]
🎱 
@joshkimmell @poofichu @mkiang3051 @scottnath - Story ready to be reviewed.

**Comment by joshkimmell** [comment]
🎱 🎱

**Comment by mkiang3051** [comment]
@ineedsubstance Are we thinking that the home page is where the user will see all of their content?

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think it's a good place, especially since that page is currently without content or purpose. But let's talk to our Content Creator users about where they might expect his content to live. We probably need a research story where we can interview or Content Creators on a variety of  UX + workflow-related questions.

**Comment by mkiang3051** [comment]
@ineedsubstance Yep! I agree. We could totally put it on the homepage, but it'd be better to do some research first. I'll look to create a research epic/stories for CMS user research.

**Comment by ineedsubstance** [comment]
@mkiang3051 - sounds great

**Comment by ineedsubstance** [comment]
Will be posting two options by end of day.

**Comment by ineedsubstance** [comment]
@joshkimmell @mkiang3051 @scottnath @poofichu @SirSpidey  -

Was able to come up with 2 options for the dashboard here. Here are some of the explanations behind each section of information.

**Message/Alert** - This would be the latest alert for this user. I think we could talk about what types of alerts/messages show up here and adding priority to certain types of messages. There is a link to "view all" that could take the user to a notification center will all messages. I really like the idea of the message is self-being interactive. The content revision or user ID being clickable.

**Activity Feed** - A list of the content the user is working on or a list of the content the "team/everyone" is working on. The idea being those users will be working on a specific piece or multiple pieces of content for a while. 

**At-a-glance** - An idea for a more visual representation of the stuff that a user might be working on. 

**Awaiting approval** - A list of content that the content creator sends into the approval workflow and can check the status and possibly in the future "resend" to the "approver" if they haven't gotten feedback within a certain amount of time. 

**Quick links** - From what I've heard, content creator frequent certain content types. This list would give those users that are in charge or frequent certain content types quick access to add content directly from the dashboard.


**v1**

![p-desktop-dashboard-v1](https://cloud.githubusercontent.com/assets/3981381/18492226/ba7a7164-79cf-11e6-8a1c-e46b509cc5ab.png)

![p-mobile-dashboard-v1](https://cloud.githubusercontent.com/assets/3981381/18492225/ba7a53aa-79cf-11e6-892f-7429c92b65f1.png)

---

**v2**

![p-desktop-dashboard-v2](https://cloud.githubusercontent.com/assets/3981381/18492237/c7a32476-79cf-11e6-9bd0-0e4283f15aab.png)

![p-mobile-dashboard-v2](https://cloud.githubusercontent.com/assets/3981381/18492236/c7a196ba-79cf-11e6-94e5-214dc1007f33.png)

**Comment by ineedsubstance** [comment]
Note: I will create another story for next sprint for comments and further interaction since this is the last day of this sprint.

**Comment by ineedsubstance** [comment]
Comments / Feedback and further interaction is being moved to new issue - #406

**Comment by SirSpidey** [comment]
feedback is on desktop only. 

### Overall
* want quick unsubscribe feature from alerts/notifications (if allowed for role) 
* Some might like to see a section of what approved content is in the queue to go live next. A table view, perhaps.


### V1
**Content approved**
* What do I do with this section or information?

**My latest**
* doesn't show the content type of the work. 
* label might need to be more specific about approved edits. For example, "[My] Latest approved changes"

**Awaiting approval**
* Will want to see info about when the content is scheduled to go live (so I know if I need to bug the approver) and perhaps have table sorted by next scheduled at the top. 
* How do we show multiple approvers?
* Might need to see info about my content that's not ready to publish yet.

**Quick links**
* I like quick links (as favorites) and would want to be able to make my own. 
But I want to go into a service/api, not a content type. I don't think in content types, I think in services. (That might be a wox-cms customization.)


### V2
I like **At a glance** 

**Activity Feed**
Not sure why approved content is in there if this is stuff I'm working on. I would want to see content that's not ready to publish.

**Comment by ineedsubstance** [comment]
Thanks, @SirSpidey.

### Overall

* When you say unsubscribe from alerts/notifications, do you mean via email? Is your expectation that this happens on the dashboard or elsewhere?
* In v2, the "Awaiting Approval" section could possibly support this. We would just need to change the name which is just a placeholder anyways.

### V1

**Content approved**
* The "content approved" is an alert/notification. In this case, it is telling the user that a piece of content was approved. Main CTA would be to view the content.

**My latest**
* Oh, ok. So it's important to always reference the content type when listing out content in this use case? 
* Idea for "My latest" is it would show everything you are working on. So stuff that is still a "draft" and stuff that is in various stages of the publishing workflow.

**Awaiting approval**
* Nice, good call. Will add sunrise date to this view.
* Good question on the multiple approvers. This will be something we discuss with you next week, but would the contnet be sent to multiple "approvers" at the same time, or one at a time?
* Content not ready to be pulblished that you are still working on would live in "My latest".

**Quick links**
* Yeah, that's interesting. What about a default based on use but a way to make your own as well?
* OK, that does seem WOX specific, but could be an interesting feature to add.

### V2

**Activity Feed**
* Your right, that's just a mistake on my part. I will update that "status" on the mockup.
