### ISSUE TITLE
Content Creator: Display content creators email

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#234]
_As a_ Content Creator, _I want_ to identify who created a piece of content _so that_ I know who to contact if I have any questions.

```gherkin
Feature: Display content creators email
  As a Content Creator,
  I want to identify who created a piece of content
  So that I know who to contact if I have any questions.

  Scenario: Content table
    Given I am working with a team of other content creators
      And that I may have a question
     When I view a list of content
     Then I will see the content creators email address for each piece of content
```

---

**Display content creators email:**
- [ ] Content table

![screen shot 2016-08-10 at 11 19 01 am](https://cloud.githubusercontent.com/assets/3981381/17561690/d79ff604-5eec-11e6-90a6-fa27b3cb20e5.png)

**Comment by mkiang3051** [comment]
@ineedsubstance Do you think this issue covers displaying the name of the content creator? I am going to link that UX flow bullet point from the wiki here for now. Maybe we can add a scenario for content creator name if we want to include that too (if email doesn't suffice / is hard to interpret).

**Comment by ineedsubstance** [comment]
@mkiang3051 - We only have the users email at this point, which should be good for now. We can revisit in the future if we think it's important to collect/show more than just the email.

http://watson-cms.stage1.mybluemix.net/users

**Comment by ineedsubstance** [comment]
@joshkimmell @mkiang3051 @poofichu @scottnath - This story is ready to be reviewed.

**Comment by joshkimmell** [comment]
🎱 🎱

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu @mkiang3051 @scottnath -  Pretty straight forward I think, but let me know your thoughts.

In the mock, the author's user ID is linked. This would be a future addition if it makes sense, and I will create a story for it. The idea is that users would be able to see all content by that Author by clicking on that link.

<img width="1277" alt="screen shot 2016-08-29 at 3 46 43 pm" src="https://cloud.githubusercontent.com/assets/3981381/18066988/66e75e0c-6e00-11e6-8adf-d0910b8a08a1.png">

**Comment by joshkimmell** [comment]
@ineedsubstance: This is a good solution. It needs a story for Scott to do some backend work.
