### ISSUE TITLE
Workflow Checks

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#236]
Currently all revisions have an approve button next to them. This needs to be cleaned up and made more clear what revisions can and cannot be put through the revision process. A longer discussion on a UI for content revisions that are available to be published and their steps should probably be considered too.

```gherkin
Feature: Workflow Kickoff
  As a Content Creator
  I want to know whether a revision can be published
  So that I know it can be sent to a workflow

  Scenario: Publishable
    Given that there are saved revisions of a piece of content
      And I am looking at the listing of available revisions
     When I want to send a revision to the workflow approval process
     Then I should only be able to send revisions that are ready to be published
      And it should be clear if a revision is not ready to publish
      And I should see which step of the approval process a revision is in
      But I should not be able to send a revision to be published if it has already passed through a workflow
      And I should only be able to send a revision to approval from the listing of revisions
```

---

**Workflow Kickoff**
- [x] Publishable

**Comment by scottnath** [comment]
@Snugug Looks good

is this correct?
1. user completes work and is ready for approval
2. user clicks "send to {{xyz}}" button (not `save revision`)
3. listing of revisions changes to reflect this content is ready for approval
  * what `step` does the revision list show for this revision?
  * does the revision list use the step content titles?

**Comment by Snugug** [comment]
Updated the story. This story is specific to looking at the listing of available revisions for a piece of content, so only content not already in the workflow process.
