### ISSUE TITLE
Core Developer: Local File Storage

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#243]
This is a technical story for implementing local file storage.

``` gherkin
Feature: Local storage
  As an administrator
  I want a local directory to store content-files
  So that the files have a permanent, safe location

  Scenario: Local storage
    Given that I need to work on the CMS in a local environment
      And when working locally, I may not have access to the internet
     When working locally on the CMS
     Then I need to have a way to store content-files locally
      And this location should be at the root level of the app
      And the storage of files should be done asynchronously. 

  Scenario: Put
    Given that I am uploading a file with my content
     When I save my content
     Then the file should be saved in my local storage
      And references to and data about the file should be stored with the content
```

---

**Local Storage**
- [ ] Local storage
- [ ] put

**Comment by scottnath** [comment]
Story re-written. No longer a blocker.

**Comment by Snugug** [comment]
I don't like these scenarios. Local storage is fine, but these scenarios assume that everyone will be using S3 for their file storage and that local storage is only a thing that'll be used offline.

What we want to be doing which https://github.com/punchcard-cms/punchcard/issues/242 starts to look at (reading that one next), is creating a file storage plugin system, and have two plugins to begin with, a local file storage, and an S3 file storage, but both abstracted through an interface.

Things I'd like to see changed in these scenarios:

* Rewrite as a storage plugin
* Don't include things like `git` or `S3`
* Let user set location to store files

**Comment by scottnath** [comment]
rewrote the story to be specific to local storage only

left the `git` reference because this is a technical story and adding the local storage to .gitignore should be part of the resolving PR.

**Comment by Snugug** [comment]
Input and output scenarios are blocked on https://github.com/punchcard-cms/punchcard/issues/492

**Comment by Snugug** [comment]
Please remove environment and `git`

**Comment by Snugug** [comment]
Given https://github.com/punchcard-cms/punchcard/pull/529 can we mark this as resolved, without need for further action? No size, no milestone, just closed.
