### ISSUE TITLE
CMS User: User password management

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#247]
_As a_ CMS user _I want_ to be able to change and/or reset my password _so that_ I can regain access to my account or secure my account when needed.

```gherkin
Feature: User password management
  As a user of the CMS
  I want to be able to change or reset my password
  So that I can secure or regain access to my CMS account

  Scenario: Change/manage password
    Given that I may need/want to manage my account's password
     When I am logged into my account
     Then I am able to navigate to an area to manage my password

  Scenario: Reset password
    Given that I could forget my password
     When I try to log into my account
     Then there will be an option for me to reset my password
      And then the ability to get a temporary password emailed to me from the system
      And the ability to login with the temp password and set my own permanent password

```

---

**User password management**
- [ ] Change/manage password
- [ ] Reset password

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think this story (https://github.com/punchcard-cms/punchcard/issues/148) covers a reset of the password if the user forgets and or can't get access.

For this story, we are talking about changing a password in the CMS while the user is already logged in, right?

**Comment by mkiang3051** [comment]
@ineedsubstance Yea I think you're right! I missed Scott's issue in my hunt for a password mgt issue. I think #148 covers this. I'll close this issue.

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think that we still need a story that talks about users changing their password within the CMS.

**Comment by mkiang3051** [comment]
@ineedsubstance Ok. Reopening this! LOL

**Comment by mkiang3051** [comment]
Although, doesn't this part in #148 cover it? (See below)

 Scenario: Change my Password CTA
    Given that I need to change my password
      And that I am logged in
    When I view an admin screen for my account
    Then I will see a link to Change my Password

  Scenario: Change password
    Given that I need to change my password
      And that to avoid mistakes I should enter my new password twice
    When I enter in my new password
    Then there should be two password entry fields
      And there should be functionality to test that both are filled in identically
      And there should be an indication that shows the security level of my password.

**Comment by ineedsubstance** [comment]
@mkiang3051 - yep, your right. I guess this is a duplicate.

**Comment by mkiang3051** [comment]
@ineedsubstance Ok, closing again! LOL.
