### ISSUE TITLE
Content Creator: Display content status

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#250]
_As a_ Content Creator, _I want_ to see the status of any piece of content _so that_ I can make the best decision on what to work on

```gherkin
Feature: Display content status
  As a Content Creator,
  I want to see the status (e.g draft, waiting approval, approved) of any piece of content
  So that I can make the best decision on what to work on

  Scenario: Content table
    Given I will need to create or edit content
      And that I will want to know the contents status before working on it
     When I view a list of the content
     Then I will see the contents status 
```

---

- [x] Display content status / Content table

![screen shot 2016-08-10 at 11 19 01 am](https://cloud.githubusercontent.com/assets/3981381/17561690/d79ff604-5eec-11e6-90a6-fa27b3cb20e5.png)

**Comment by Snugug** [comment]
I believe this was resolved with https://github.com/punchcard-cms/punchcard/issues/236. Please check our running instance. If there is more to do here, please flesh out the story to describe in detail what the user expectation is.

**Comment by ineedsubstance** [comment]
Thanks, @Snugug. Yeah, looks like we are showing the status on the revisions screen now.

http://watson-cms.stage1.mybluemix.net/content/api/f82bca2a-ce61-4c01-bb87-e10abbbb2c89

![screen shot 2016-08-15 at 12 55 42 pm](https://cloud.githubusercontent.com/assets/3981381/17673852/9e61a46e-62e8-11e6-8953-3ed1daed9b9a.png)
