### ISSUE TITLE
Content Creator: Visual affordance for required fields

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#271]
_As a_ Content Creator, _I want_ to be able to identify which fields are required _so that_ I know what is expected when creating and editing content.

```gherkin
Feature: Visual affordance for required fields
  As a Content Creator,
  I want to be able to identify which fields are required
  So that I know what is expected when creating and editing content.

  Scenario: Required for saving
    Given I will need to gather content to enter into the CMS
      And that certain content is required for the content to be eligible to save
     When I look to create or edit content
     Then I will see a visual affordance for required fields
       And identify which fields I need to complete to save

  Scenario: Required for publishing
    Given I will need to gather content to enter on the CMS
      And that certain content is required for the content to be eligible to publish
     When I look to create or edit content
     Then I will see a visual affordance for required fields
       And identify which fields I need to complete to publish
```

---
**Visual affordance for required fields:**
- [ ] Required for saving
- [ ] Required for publishing

---

![screen shot 2016-08-15 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/3981381/17676056/3a6c0850-62f2-11e6-94c6-4138b67f1295.png)

**Comment by ineedsubstance** [comment]
🎱 
@poofichu @joshkimmell @mkiang3051 @scottnath - Ready for review.

**Comment by mkiang3051** [comment]
@ineedsubstance 
We're just reviewing the story right? Not the attached screenshot? 
🎱

**Comment by joshkimmell** [comment]
🎱 🎱

**Comment by mkiang3051** [comment]
So... I kind of overheard you guys talk about the 🎱 earlier before lunch. What does it actually mean? Does an 🎱  signify "It's all good! everything looks super duper!"?

**Comment by joshkimmell** [comment]
🎱  = This story is ready for review
🎱 🎱  = I agree that this story is ready to be prioritized, estimated, and moved to the backlog

**Comment by mkiang3051** [comment]
@ineedsubstance Ok cool.
@joshkimmell Oops!!! Crap, I think I was going eight ball happy on one of these stories and posted three in a row. Oops...

**Comment by ineedsubstance** [comment]
@mkiang3051 - did you do some work on this already that we can use as a jumping off point?

**Comment by mkiang3051** [comment]
@ineedsubstance Yes! Some of my screens are from this issue in WOX CMS: https://github.ibm.com/Watson/wox-cms/issues/194

However I can upload any of my screens straight to this issue if you like. The folder with all my wires is here: https://ibm.box.com/s/95hm350rx0mmk8u63xp93rm0j8k18hc1

**Comment by ineedsubstance** [comment]
This is great. Thanks @mkiang3051

**Comment by mkiang3051** [comment]
👌

**Comment by ineedsubstance** [comment]
Resources for myself:

http://usability.com.au/2013/05/accessible-forms-2-required-fields-and-extra-information/

> How to indicate a required field

> The three main ways of visibly indicating a required form field are:

> - Using the word “Required”
> - Using an inline image (often a graphic star) with an appropriate alt attribute (e.g. “mandatory form field” or “required information”).
> - Using the keyboard star (asterisk) symbol

http://webaim.org/techniques/formvalidation/

> If your form requires that certain controls be completed or selected, you should indicate this to the user in a usable, accessible, and apparent manner. These instructions should typically be located adjacent to and within the label of the required form control.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Basic_form_hints

> Web developers typically use presentational strategies to indicate required or invalid fields, but assistive technologies (ATs) cannot necessarily infer this information from the presentation. ARIA provides attributes for indicating that form controls are required or invalid:

**Comment by ineedsubstance** [comment]
@poofichu @joshkimmell @mkiang3051 @scottnath - Looking for feedback.

---
I explored many different ways of informing users that certain fields are required. This was a little tricky since our CMS has two different required fields, those that are required to save and those that are required to publish. Upon doing research, and looking at successful examples, what seemed to be clear was the two methods companies used. 1. Using the work "required". 2. Using the keyboard star "*". In most cases, next to the field label. So I explored both of these methods in a variety of ways using placement, color, and icons to produce multiple solutions.

---

**_Note: This has not gone through visual styling. Any icons, colors, fonts, sizes, etc... are just meant to illustrate an idea and are not final. Once we decide on a direction, then Jessica can tweak to fit out overall visual asthetic._**

---

![mobile-form-v1](https://cloud.githubusercontent.com/assets/3981381/18055301/e6aba000-6dcc-11e6-996d-665a7a52eb07.png)

![mobile-form-v2](https://cloud.githubusercontent.com/assets/3981381/18055302/ea654c50-6dcc-11e6-9e12-41e2d958260d.png)

![mobile-form-v3](https://cloud.githubusercontent.com/assets/3981381/18055307/edacd522-6dcc-11e6-8823-435ce4e0bc37.png)

![mobile-form-v4](https://cloud.githubusercontent.com/assets/3981381/18055313/f1eb2a30-6dcc-11e6-8a05-006a9399a6fa.png)

![mobile-form-v5](https://cloud.githubusercontent.com/assets/3981381/18055316/f56d1664-6dcc-11e6-9b79-5822d1c3d6f4.png)

![mobile-form-v6](https://cloud.githubusercontent.com/assets/3981381/18055322/f8b0017e-6dcc-11e6-9eb9-7d2e57409da9.png)

![mobile-form-v7](https://cloud.githubusercontent.com/assets/3981381/18055324/fbea7180-6dcc-11e6-8ae4-ee112dff0435.png)

**Comment by joshkimmell** [comment]
@ineedsubstance I think you're on to something with the last one. I want more of a visual affordance than an asterisk or a star... If a user is in a hurry to save something, they should be able to quickly scan the the form to make sure the required fields are filled. Less so for the publish scenario, as the user is more likely to be critical of the content before submitting to be published.

**Comment by ineedsubstance** [comment]
There is something else to consider, that @mkiang3051 and I discussed when looking at our research stories, is this idea of knowing when the user is "done" or ready to publish. Some of these forms could be pretty big, so scanning the form to find these required fields might be pretty daunting. Having an indicator or progress bar related to how close the user is to saving or publishing could also be something to explore.

**Comment by joshkimmell** [comment]
@ineedsubstance: sure. Write another story for that one, though, as that is new functionality. This one can be done with CSS.

**Comment by joshkimmell** [comment]
![image](https://cloud.githubusercontent.com/assets/8161298/18059100/f7bcb8c4-6ddc-11e6-81fb-7dd3b38c731c.png)

This is just to show how easy it would be to show save vs. publish required fields. I don't think this is the solution, as there needs to be more than a color difference...

**Comment by poofichu** [comment]
I like the last one too, except we need to add something other than color to indicate a required field for those with visual impairments.

**Comment by joshkimmell** [comment]
I do like the combination of field style and label text...
![image](https://cloud.githubusercontent.com/assets/8161298/18059212/8c93a854-6ddd-11e6-91fc-cb2fd85c516c.png)

**Comment by ineedsubstance** [comment]
@poofichu - Exactly right that color is not enough, that's why every option I showed used the words "required" or a "*" along with some visual elements. I'm personally a fan of using text (required to save) along with some visual styling. The trick is being clear and scannable, but not overdoing visually to where it detracts the users to completing their goal. 

@joshkimmell - Yes, I'll write that story.

**Comment by mkiang3051** [comment]
@ineedsubstance I agree with everyone else - your last example with the color and the label is nice! I do like seeing the requirements typed out, rather than having a key somewhere on the page telling you what a symbol means.
And the color is a nice touch for those of us who can see the color. And if we do use color, we can make sure to make them different enough and accessible on the spectrum for those who may be colorblind.
