### ISSUE TITLE
Bug: A11Y Problem with Checkbox Styling

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#275]
When tabbing through a form, checkboxes (and presumably radios) don't tab. This is due to them having **[display](https://github.com/punchcard-cms/punchcard/blob/57f173f9c4476b2c0a13f7a21439f3020d950634/src/sass/partials/global/_mixins.scss#L54-L55): [none](https://github.com/punchcard-cms/punchcard/blob/57f173f9c4476b2c0a13f7a21439f3020d950634/src/sass/partials/global/_mixins.scss#L130-L131)** set. These need to be visually hidden, not removed entirely.

## Steps for Reproducing

- Go to a content type with checkboxes
- Try and tab to a checkbox
- Notice it skipped

## Screenshots

![Can't Tab to Checkboxes](https://cloud.githubusercontent.com/assets/377188/17710154/0d25eb7c-63ba-11e6-8243-6847959b4ede.gif)

## Affected Browsers

- [ ] Chrome
- [ ] Firefox

(presumably all others)

## Runtime Version

v5.11

## Code Version

Latest

**Comment by joshkimmell** [comment]
moving to the next sprint
