### ISSUE TITLE
Database for CI and local development

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#283]
A large problem we run into is the use of postgres when creating our testing. When developing locally it writes to the local database and when errors happen, those entries are not automatically removed. For CI, the postgres timeouts often lead to failing builds - when there is nothing wrong with the build.

```gherkin
Feature: Data storage alternative for testing
  As a core developer
  I want data storage for development purposes
  So that I can develop my application with minimal storage issues.

  Scenario: Local development
    Given that we must develop locally
      And that we need to continually run tests while developing
      And that using the localhost database may cause errors when tests fail and do not trigger a removal of test data
      And that when running tests we need the option of adding and removing entries
    When I am running unit tests locally
    Then I need a data storage option that mimics the functionality of our production database
      And this option needs to seamlessly work with knex
      And this option should be configurable via the global configuration
      And this option should be separate from the database used when Punchcard is running on localhost.      
```

---

**Data storage alternative for testing**
- [ ] Local

**Comment by Snugug** [comment]
I… don't understand this issue? We don't touch data storage with our DB. It's a database. I also would like these scenarios rewritten to discuss the actual context, action and expected results that need to be resolved

**Comment by scottnath** [comment]
I meant database (changed title)

**Comment by Snugug** [comment]
The tests I wrote for API generates fake content before it starts and removes it from the DB after it's done; if the problem is our tests need content, we should do that for all of our tests

**Comment by scottnath** [comment]
Did you read the opening description?

**Comment by Snugug** [comment]
I did, it's not clear that is the problem, and the scenarios are not clear. Can you please take another swing at them?

**Comment by Snugug** [comment]
Also, it sounds like the problem exists with Travis. If that's the case, we should have a `before_script` script that drops all tables in our DB for Travis before this starts, and this now sounds like a bug

**Comment by scottnath** [comment]
removed ci, re-wrote scenario

**Comment by scottnath** [comment]
@Snugug I think this is as simple as setting up a separate database in the config for local testing. We could probably just change [this section](https://github.com/punchcard-cms/punchcard/blob/master/config/test.js#L7) to allow this db to be used for local testing too. I'm gonna make this a `2` because I want to experiment a bit with it.
