### ISSUE TITLE
UX Researcher: Research user needs around editing content

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#295]
We want to understand our users' needs around editing content.

---
### Accessing own content
- View authored content vs. any content touched? Or both?
- Investigate user workflows around: edited content
- Expectations around viewing their own content
### Editing content
- Saving (autosave/manual saves?) 
- Minimum content required/available
- Knowing when content is finished/done (what is the definition of "done" per content type?)
- Dependencies to publish (depending on readiness related content)
- Previewing content that you have
- Easily find/view/hop to various input types (without having to scroll manually)?
### Sorting and filter content
- Ability to sort and/or filter content

**Comment by ineedsubstance** [comment]
@mkiang3051 -all the stories in the EPIC are closed, can we close this EPIC?

**Comment by mkiang3051** [comment]
Yep, close it. We can reopen later if we need.
