### ISSUE TITLE
UX Researcher: Research user needs around content types

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#297]
We want to get some insight into how users will interact with our content types and if they are consumable for our content creators and editors as they are currently designed in the CMS.

---
### Taking actions on a content type
- What actions would you want to take? (View all content? Create new? View last published? Etc.)
### Information about content type
- Expectations around what they would see regarding a content type (descriptions?)
- Content type list presented to user (everything? or specific to a role?)

**Comment by ineedsubstance** [comment]
@mkiang3051 -all the stories in the EPIC are closed except #437, can you look at that story and see if we still need it. If not, we can probably close this EPIC as well.

**Comment by mkiang3051** [comment]
@ineedsubstance We can close this EPIC. #437 was actually not finished because we didn't get any data on content types in our first interviews with Jeremy and Allen.

**Comment by ineedsubstance** [comment]
Do you see #437 as something that we still need since this project is not being used for WOX anymore?

**Comment by mkiang3051** [comment]
I would say no since this is a research synthesis story on data we haven't yet collected.
Our specific content types were created for internal use with our content creators - so #437 was aimed at synthesizing feedback on the types of content they would need to see populated in the CMS, and how they work with/take action on those content types.
