### ISSUE TITLE
UX Researcher: Research user needs around content creation

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#301]
We want to understand our users' needs around content creation.

---
### Creating new content
- Saving (autosave/manual saves?) 
- Minimum content required/available
- Knowing when content is finished/done (what is the definition of "done" per content type?)
- Dependencies to publish (depending on readiness related content)
- Previewing content that you have
- Easily find/view/hop to various input types (without having to scroll manually)?

**Comment by ineedsubstance** [comment]
@mkiang3051 -all the stories in the EPIC are closed, can we close this EPIC?

**Comment by mkiang3051** [comment]
Yep, close it. We can reopen later if we need.
