### ISSUE TITLE
UX Researcher: Research user needs around managing users in a team

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#302]
* what is everyone working on
* adding new users
* managing users
* content team view

**Comment by mkiang3051** [comment]
@ineedsubstance 
I think this may be related to this issue I had created: https://github.com/punchcard-cms/punchcard/issues/294

Do we want to keep this one? Or break the items up a bit when we flesh them out?  Mine seems to be a bit more specific than yours - but is intended to center around user role access/mgt. 

Let me know your thoughts!

**Comment by mkiang3051** [comment]
Closing duplicate - see https://github.com/punchcard-cms/punchcard/issues/294
