### ISSUE TITLE
UX Researcher: Finding internal users to interview - Round 1

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#321]
_As a_ UX Researcher _I want_ to find possible interviewees _so that_ I can speak to them to find out about their user needs, expectations and workflows as it relates to using a CMS.

```gherkin
Feature: Finding interviewees
  I want to find interviewees to contact
  So that I can speak with them about their user needs, expectations and workflows as it relates to using a CMS

  Scenario: Contact Jeremy / Marketing
    Given that our internal IBM marketing team will be a main user of the WOX CMS
      And that they will be creating/editing all the marketing content that goes on WOX
     Then I should contact a representative from the Watson marketing team to see if I can get a list of possible people marketing content creators to interview.

  Scenario: Contact Allen / ID Team
       Given that our internal IBM ID team will be a main user of the WOX CMS
      And that they will be creating/editing all the API/service related docs content that goes on WOX
     Then I should contact a representative from the Watson ID team to see if I can get a list of possible people technical writers to interview.

  Scenario: Contact Allen / Service OMS
       Given that our internal IBM service OMs will be a user of the WOX CMS
      And that they will be reviewing/editing some API/service related content that goes on WOX
     Then I should contact a representative from the Watson ID team to see if I can get a list of possible OMs to interview.

  Scenario: Create list of users to speak with
       Given that we will have collected a list of possible CMS users to speak with
      And that we will be reaching out to interview them in the future
     Then I should create a list of all users to speak with so I can schedule time to speak with them

```

---

**Finding interviewees**
- [x] Contact Jeremy/marketing
- [x] Contact Allen/ID team
- [x] Contact Allen/service OMs
- [x] Create list of interviewees

--- 

**List so far**
Box link: https://ibm.box.com/s/fx4pcwfrka67kwok0etky29kh2w4mcqu

#### ID/Docs
* Allen Dean, Information Development (allen.dean@us.ibm.com)

#### Marketing/Content strategy
- [ ] Jeremy Hodge, Web and Digital Marketing Lead (jeremyh@us.ibm.com)
- [ ] Lecia Papadopoulos, Content Manager for Watson Explorer (woodle@us.ibm.com)

**Comment by mkiang3051** [comment]
@ineedsubstance @joshkimmell @poofichu 
I just fleshed this super simple story out a bit. I put down Jeremy for marketing and Allen for ID. Are there any other internal users we can contact to interview/get an interview list from? 

Thanks team!

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think we need OM as well and we can ask Allen / Jeremy who they might recommend.

**Comment by mkiang3051** [comment]
@ineedsubstance 
Thanks! I felt like I was forgetting someone important. :D Will add that.

**Comment by mkiang3051** [comment]
Added another point to this issue - sent out the emails and will wait to see what users we can contact
