### ISSUE TITLE
Check url parts

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#331]
I need to test various parts of a url to confirm they are indeed the correct type of information. 

```gherkin
Feature: URL in request
  As a core developer
  I want a request's URL to be checked for errors
  So that I can avoid badly-formatted urls throwing unknown errors.

  Scenario: type
    Given I have a request object with a url in it
      And that it should be a url with multiple parameters
      And that one of those parameters is a content type's id
      And I have an object containing all content types associated with my application
     When testing the content type's id parameter 
     Then I need to test that the id is a string
      And I need to test that the id matches an id of an associated content type
      And I need to receive the matching content type object
      Or I need to receive an error message.

  Scenario: id
    Given I have a request object with a url in it
      And that it should be a url with multiple parameters
      And that one of those parameters is a piece of content's id
     When testing the parameters
     Then I need to test that the id is a string
      And I need to test that the id is in uuid format
      And I need to receive a confirmation that it is a uuid string
      Or I need to receive an error message.

  Scenario: revision
    Given I have a request object with a url in it
      And that it should be a url with multiple parameters
      And that one of those parameters is a revision number
     When testing the parameters
     Then I need to test that the revision is a string
      And I need to test that the revision is a number
      And I need to receive a confirmation that it is a number and a string
      Or I need to receive an error message.

  Scenario: url
    Given I have a request object with a url in it
      And that it should be a url with multiple parameters
      And that each of those parameters must match certain formats and types
     When receiving a request
     Then I need to test the parameters of the url
      And if those parameters all pass I need the request object changed
      And I need that change to include the full object of the content type referenced by the url
      Or I need to receive an error message.
```

---

**URL in request**
- [x] type
- [x] id
- [x] revision
- [x] url

**Comment by Snugug** [comment]
What's the estimate for this?

**Comment by Snugug** [comment]
@scottnath Getting better with the gherkin, but this is very implementation-heavy. I'd like to see this written more from a user perspective in the future. Something like this:

```gherkin
Scenario: Type
  Given that a URL may contain multiple dynamic parameters
    And I know what all of the available full content types are
   When I navigate to a content-based URL
   Then I can ensure that the URL's dynamic parameters contains a valid content type
    And I can receive the full content type from the URL
    And I will receive an error if the content type is not valid
    And I will receive an error if I cannot retrieve the full content type
```

Also, `Or` is not allowed as a keyword, only `And` and `But`

**Comment by scottnath** [comment]
Requires further conversation...

In this scenario I _did_ mean for the persona to be the Core Developer. That is the only [persona](https://github.com/punchcard-cms/punchcard/wiki/Personas) that would be able to break down the needs of testing a url as all of the checks that need to happen are backend-specific.

For instance, the id of a piece of content is in uuid format. The _only_ place the format of the id representing a piece of content is relevant is within the back-end code. No user would need to know that - so if we were writing these scenarios from a Content Creator's POV - how could I determine the LOE unless I broke down the specifics of what I needed the system to do as above? Otherwise one would expect I'd be back-of-the-napkin-ing my plan for what I'm going to test for each section of the path.

So, with that in mind, I wrote these scenarios not with implementation details, but more as "if I give this to the system, I should get that out of the system". I was attempting to think of this task according to it's i/o interfacing (why I use `request object with a url` as opposed to a `url`) . To it's logical conclusion - ie if we plan on using our gherkin as a testing code skeleton - we would need this level of understanding to know if this one portion of our code is performing the specific need we require of it. 

The scenario example you've added would have no need to take into account requirements like whether a revision is a number and not a string. Nor is it correct in it's assumption that the user would receive the full content type from the url. The _system_ does get and manipulate the content type - but the user would only see a portion of that.

I know there is way more to this, and that this is meant to be about business logic and the user's needs. I'm just coming at this from the idea that if you flip the system inside out, then there are plenty of user needs from the standpoint of the core developer. And those needs can have clear `Given/When/Then` scenarios that are not specific to implementation (although they may sound that way to a layperson).

This is an amended version, removing the _or_:

```gherkin
  Scenario: id
    Given I have a request object with a url in it
      And that it should be a url with multiple parameters
      And that one of those parameters is a piece of content's id
     When the system reads the url to determine the proper route to process
     Then I need to confirm that the id is a string
      And I need to confirm that the id is in uuid format
      And I need to receive a confirmation that it is a uuid string
      But I should receive an error message if it is not a uuid string.
```

**Comment by Snugug** [comment]
`contains a valid content type` would cover it from a Gherkin perspective, it would be up to implementation to define what `valid` means.

As for users, Core Developer is a user, so it would be from their perspective. Scenarios should never be from the perspective of the system

**Comment by Snugug** [comment]
We still need a size for this as well; shouldn't be worked on w/o a size
