### ISSUE TITLE
Content Creator: Visual affordance for required fields - R2

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#336]
_As a_ Content Creator, _I want_ to be able to identify which fields are required _so that_ I know what is expected when creating and editing content.

```gherkin
Feature: Visual affordance for required fields
  As a Content Creator,
  I want to be able to identify which fields are required
  So that I know what is expected when creating and editing content.

  Scenario: Narrow down options for required fields affordance
    Given I will need to gather content to enter into the CMS
      And that certain content is required for the content to be eligible to save
     When I look to create or edit content
     Then I will see a visual affordance for required fields
       And identify which fields I need to complete to save
       And identify which fields I need to complete to publish
```

---
**Visual affordance for required fields:**
- [x] Narrow down options for required fields affordance

---

Reference #271

**Comment by ineedsubstance** [comment]
Would love to get everyone's feedback here. My preference is v3 or v7. I think spelling out what is required is key and accessible. Add the clear text with some sort of visual indicator will help users see what is required at a glance. cc/ @joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey

Posting options here as well:

**v1**
![mobile-form-v1](https://cloud.githubusercontent.com/assets/3981381/18136619/0ca91fc2-6f6b-11e6-8e3e-fa107a86a337.png)

**v2**
![mobile-form-v2](https://cloud.githubusercontent.com/assets/3981381/18136624/12b253d4-6f6b-11e6-99d0-53b0ad559f1b.png)

**v3**
![mobile-form-v3](https://cloud.githubusercontent.com/assets/3981381/18136634/1834ecea-6f6b-11e6-8cf2-965e58f01210.png)

**v4**
![mobile-form-v4](https://cloud.githubusercontent.com/assets/3981381/18136636/1c040b08-6f6b-11e6-91d9-803deeb8e05e.png)

**v5**
![mobile-form-v5](https://cloud.githubusercontent.com/assets/3981381/18136642/20b4fdd8-6f6b-11e6-9dc9-711cc8f0499f.png)

**v6**
![mobile-form-v6](https://cloud.githubusercontent.com/assets/3981381/18136649/24e6aeec-6f6b-11e6-8742-e7e90dcfa53f.png)

**v7**
![mobile-form-v7](https://cloud.githubusercontent.com/assets/3981381/18136654/293bcf04-6f6b-11e6-8285-1592eb787d5b.png)

**Comment by mkiang3051** [comment]
@ineedsubstance I really like v7! I think having text written out, but with an easier (IMO) to see visual cue on the actual input field area is nice.

On a tangent, V5 kind of reminds me of Dragon balls. 
![image](https://cloud.githubusercontent.com/assets/5656022/18146642/6aa60dbc-6f96-11e6-8d6c-3e116f29f3e7.png)

**Comment by joshkimmell** [comment]
@ineedsubstance: As stated in #271, I'm fine with v7, but there needs to be more blatant diff between the 2 required fields and the non-required fields. Also, the teal doesn't have enough color contrast again the background.

**Comment by ineedsubstance** [comment]
Thanks @mkiang3051 + @joshkimmell.

Josh, what do you mean by blatant difference? If you are just talking about which colors to choose for each, then @poofichu should be able to explore that in the visual stage.

**Comment by joshkimmell** [comment]
I mean other than color, how can the user scan the form and easily differentiate between required to save and required to publish?

**Comment by SirSpidey** [comment]
Wonder if we could use a different staged treatment:
1. Never been saved: show only required to save. These are the only required ones to get me started.
2. Already saved: highlight required to publish, still show (*) required to save.
This would mean errors if you click publish before save. Not sure how often that will happen.

---

* Can't rely only on color alone (accessibility), but I like color diffs
* V6: don't like the same treatment on required to save and publish
* Older IBM guidelines used an asterisk for required fields and I'm used to scanning for that. So that turns me away from v2, v3, and v7.

**Comment by ineedsubstance** [comment]
@SirSpidey - I think it might be difficult to know the user's intent (if they want to only save not publish) upon first use, especially for all content types. I do think there could be some sort of mechanism, like a link, that would highlight all fields that were required to save or publish so the user could request that information. Also, we discussed having an indicator of how many fields were required to save or publish, and how many user had filed out. Sort of like a progress indicator (e.g. 5 of 10). We could explore both these options, but it would be another story, though.

I think what I can do is narrow this down to 2 versions and we can test this with real users to see which is more clear.

**Comment by ineedsubstance** [comment]
Working on 2 new versions based on v7 as options. Will post those on Monday.

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey: Feedback needed.

I took v7 from above and applied that visual affordance to the API form so we could see how the required and save patterns might look to the user as they land on the page and as they scroll down. I also created 2 other options using the "required to publish" text and different color visual affordance styles. 

* Keep in mind that @poofichu will still need to make final visual tweaks with regard to color, type, size and placement for whichever option we go with.

---

**v1 - color bar on left side of input + required text highlight**

![desktop-form-v1](https://cloud.githubusercontent.com/assets/3981381/18443560/091dc316-78db-11e6-919e-7a6ddb0865a4.png)

**v2 - color border on input + required text highlight**

![desktop-form-v2](https://cloud.githubusercontent.com/assets/3981381/18443573/11d3be8e-78db-11e6-884f-8a19b7d7befc.png)

**v3 - label + required text underline**

![desktop-form-v3](https://cloud.githubusercontent.com/assets/3981381/18443580/19afba04-78db-11e6-86eb-5b855f465ae7.png)

**Comment by SirSpidey** [comment]
I agree with Miranda for v1 as I look at mockups.

@mkiang3051 interesting idea about toggle/hiding fields you don't want to fill out. That might be helpful because the form contains a mix of fields that aren't related to any workflow. So, I'd like to filter by fields needed to create/update an API "landing page" (not the "API reference" fields).

**Comment by ineedsubstance** [comment]
Thanks @SirSpidey + @mkiang3051. I agree that the toggle would be an interesting idea. I think it would still need to be a secondary way of discovering which fields are required for what. I don't like the idea of hiding or abstracting what is required until a user clicks on something, but if we have that as an additional way to clarify or filter the fields required to "save" for example, that could be cool.

Also, thought about the idea of a progress bar of sorts to give a visual reminder to a user how many fields they have left before they can "publish" the content. 

I think both these enhancements could be another story to flesh out further.

**Comment by mkiang3051** [comment]
@ineedsubstance 
Yep - toggle would definitely be secondary - and we'd need to test out what filters would be needed/useful. 
Progress bar is an interesting idea. I'm thinking if we had a progress bar, it would need to follow the user as they progress down the page, so it would be viewable wherever the user is.
We would also need to state explicitly that the progress bar would display progress for either filling out fields to completion for `publishing` (or whatever we decide to use it for) - and not have users think it would tell them when their job of filling out the fields they need to is done. 

@SirSpidey I like that thought about making it even easier for the user to see the items that may be relevant to the content they are entering. We'll have to vet it out and mock it up and see if it would be helpful, but I think brainstorming up ways to not make the forms look so intimidating (and involve so much scrolling) can definitely help the user! 

Yay for possible enhancements! 💃

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu - can I get some feedback from you 2 please.

**Comment by joshkimmell** [comment]
V1 is good. We can mess with the styles later if it's not working for peeps. Let's leave the toggle idea for another, less stressful time. 

👍

**Comment by ineedsubstance** [comment]
ok, V1 it is.

Implementation story here for next sprint - #404
