### ISSUE TITLE
Content Creator: Verify I am logged in - R2

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#337]
_As a_ Content Creator, _I want_ my Account ID (email) to be visible after I log in _so that_ I can verify that I am logged in as me.

```gherkin
Feature: Verify I am logged in
  As a Content Creator,
  I want my Account ID (email) to be visible after I log in
  So that I can verify that I am logged in as me.

  Scenario: Expose my Account ID (email) further exploration
    Given that, I am logged into the CMS
      And that I entered my account email to log in
     When I navigate the CMS
     Then I will be able to verify the account that I am logged in as
       And that my Account ID (email) will be visible on every page I navigate to
```

---

**Verify I am logged in:**
- [x] Expose my Account ID (email) further exploration

---

Reference #217

**Comment by ineedsubstance** [comment]
Need feedback on the options I created in #217 and if I need to continue iterating or if we can come to a consensus. cc / @joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey

My opinion is v1 or v4 on Mobile and v1 on Desktop. I think these options solve the issue of exposing the account ID, and allow for maximum flexibility as we continue to add to the navigation in the future.

---

## MOBILE

![punchcard-mobile-v1](https://cloud.githubusercontent.com/assets/3981381/18139264/4e036c74-6f76-11e6-8e56-80b292cc358a.png)

![punchcard-mobile-v2](https://cloud.githubusercontent.com/assets/3981381/18139266/4e03f41e-6f76-11e6-853d-3861b7ca50dc.png)

![punchcard-mobile-v3](https://cloud.githubusercontent.com/assets/3981381/18139265/4e03ea6e-6f76-11e6-9264-3e25e59a0902.png)

![punchcard-mobile-v4](https://cloud.githubusercontent.com/assets/3981381/18139263/4e029da8-6f76-11e6-9791-66e7311cad93.png)

![punchcard-mobile-v5](https://cloud.githubusercontent.com/assets/3981381/18139267/4e03e7bc-6f76-11e6-982e-2e68117b2a19.png)

![punchcard-mobile-v6](https://cloud.githubusercontent.com/assets/3981381/18139268/4e0576f4-6f76-11e6-8022-9284cc8732fb.png)

![punchcard-mobile-v7](https://cloud.githubusercontent.com/assets/3981381/18139269/4e232492-6f76-11e6-92ec-c31df012d3c3.png)

---

## DESKTOP

![punchcard-desktop-v1](https://cloud.githubusercontent.com/assets/3981381/18139281/5c64f38c-6f76-11e6-9c94-31b20a4a2da3.png)

![punchcard-desktop-v2](https://cloud.githubusercontent.com/assets/3981381/18139279/5c636ddc-6f76-11e6-965a-b0c4bbac3ae1.png)

![punchcard-desktop-v3](https://cloud.githubusercontent.com/assets/3981381/18139280/5c63c160-6f76-11e6-9715-626438ba540a.png)

**Comment by mkiang3051** [comment]
@ineedsubstance I also like V1 and V4 for mobile, and V1 for desktop. I really like the icons in the menu for mobile V4!

**Comment by SirSpidey** [comment]
* like v2 more than v1 in desktop
* don't like placement in v3 for desktop

don't expect to do this in mobile, so don't care.

**Comment by ineedsubstance** [comment]
Thanks @mkiang3051 + @SirSpidey

**Comment by ineedsubstance** [comment]
@joshkimmell or @poofichu - can I get your thoughts on this please.

**Comment by Snugug** [comment]
@ineedsubstance Which one is the final version? Something should only be `in review` if we're looking to approve the final version. If you'd just like some comments, add the `request for comments` label

**Comment by joshkimmell** [comment]
I like v1 mobile + v2 desktop

**Comment by ineedsubstance** [comment]
OK, v1 on mobile and v2 on desktop it is.

Implementation story is here - #405
