### ISSUE TITLE
Content Creator: identify where I am and navigate with ease - R2

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#338]
_As a_ Content Creator, _I want_ to be able to identify where I am and where I've been in context to the site _so that_ I can easily navigate the CMS and so I can retrace my steps if I need to go back.

```gherkin
Feature: Identify where I am and navigate with ease options feedback
  As a Content Creator,
  I want to be able to identify where I am and where I've been in context to the site
  So that I can easily navigate the CMS 
    And so I can retrace my steps if I need to go back.

  Scenario: Provide Location-based breadcrumbs
    Given that, the CMS is complex and has multiple levels of content
       And I may need to retrace my steps when trying to accomplish a task
     When I navigate the CMS
     Then I will get a clear idea of where I am in the website’s hierarchy 
       And a clear indicator of the current page I am on
       And the ability to navigate back one or more levels at any point
```

---

**Identify where I am and navigate with ease options feedback:**
- [x] Provide Location-based breadcrumbs

---

Reference #219

**Comment by ineedsubstance** [comment]
Requesting feedback on the options I created in #219 and if I need to continue iterating or if we can come to a consensus. cc / @joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey

Not a huge difference in all the version, but I prefer v3. I think @poofichu could make the call on using a `/` vs a `>`, but I think v3 solves the user problem and should give them a clear idea of where they have been and how to get back.

---

**v1**
![mobile-breadcrumbs-v1](https://cloud.githubusercontent.com/assets/3981381/18139711/2aecf58c-6f78-11e6-8140-36a66b093600.png)

![desktop-breadcrumbs-v1](https://cloud.githubusercontent.com/assets/3981381/18139710/2aec11ee-6f78-11e6-926f-2ffd96355318.png)

**v2**
![mobile-breadcrumbs-v2](https://cloud.githubusercontent.com/assets/3981381/18139728/3e9e2d58-6f78-11e6-9430-b388b4354b90.png)

![desktop-breadcrumbs-v2](https://cloud.githubusercontent.com/assets/3981381/18139727/3e9df752-6f78-11e6-8174-b268d1a02e40.png)

**v3**
![mobile-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18139737/47a6543e-6f78-11e6-903f-a31980db29ff.png)

![desktop-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18139736/47a54f80-6f78-11e6-8d36-9a36c6a256cd.png)

**v4**
![mobile-breadcrumbs-v4](https://cloud.githubusercontent.com/assets/3981381/18139751/50a192e2-6f78-11e6-9a00-ebdfa633fd8b.png)

![desktop-breadcrumbs-v4](https://cloud.githubusercontent.com/assets/3981381/18139752/50ba95c6-6f78-11e6-8945-165415f37242.png)

**Comment by mkiang3051** [comment]
@ineedsubstance I think the structure of the breadcrumb on V3 makes the most sense. I, myself, personally think the little ">" makes a bit more sense, but it'll be fine whichever solution/design we go with.
To confirm: is `home` synonymous with `dashboard`?

Also: Are V1 and V2 just showing the visual differences in using ">" vs. "/"?
And then V3 and V4 are actual different ways of displaying the breadcrumb taxonomy?

**Comment by ineedsubstance** [comment]
Thanks @mkiang3051. 

Also, yes to both your questions.

**Comment by SirSpidey** [comment]
I don't have strong opinions about / v. >, yet am used to seeing >

**Observation**
I don't think that the only way to get to a page will be by clicking down the hierarchy, so the breadcrumb might not actually be the way to get "back" to where I came from. For example, if I have some "task" on my dashboard that takes me to a page directly, I might drop down several levels in the breadcrumb with one link.

**Comment by ineedsubstance** [comment]
Interesting point @SirSpidey. 

The purpose of location-based breadcrumbs which is my recommendation is to show the user where they are in the website’s hierarchy. Since there are multiple levels attached to our editing and revising content, I thought this approach made the most sense. If we were using path-based breadcrumbs, that would show the steps a user has taken to arrive at a particular page which is more inline to what you are describing.

**Comment by ineedsubstance** [comment]
Last call here (@joshkimmell @poofichu @scottnath @mkiang3051 @SirSpidey), but I think v3 is the solution we should go with for now. We can always iterate in the future once we get this in our user's hands. 

I will create a story for the visual design and for technical implementation.

**v3**

![mobile-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18391636/36df259c-7674-11e6-98de-012b73151292.png)

![desktop-breadcrumbs-v3](https://cloud.githubusercontent.com/assets/3981381/18391641/3a77c98e-7674-11e6-8ccf-41794a2c795c.png)

**Comment by mkiang3051** [comment]
@ineedsubstance 
I'm cool with moving forward with V3. Not sure if you saw my Slack post a couple days ago, but Apple has their breadcrumb at the BOTTOM of their page on mobile. Which I thought was odd! 🍏

**Comment by Snugug** [comment]
@ineedsubstance If that's what we're going to go with, please issue a PR to get the update in to Punchcard

**Comment by ineedsubstance** [comment]
@Snugug - I happy to create a PR, but want @poofichu to provide input from a visual perspective. Also, I couldn't get Punchcard setup locally yet (running into similar setup issue as Jessica and Josh), so what are you are seeing are just mockups.

**Comment by ineedsubstance** [comment]
#398 - visual styling story.
#399 - implementation story.
