### ISSUE TITLE
UX Researcher: Creating Research Questions/Research Plan

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#355]
Creating research questions and research plans for covering the following CMS user research topics:
* User roles + team mgt (#294)
* (Approval) workflows (#296)
* Content creation (#301)
* Editing content (#295)

---

* Content types (understanding/navigating to content types) (#297)
* Alerts + notifications (#300)
* First time experience on the CMS (#341)
* Searching for content (#299)

**EDIT:**  I had initially split the research questions and plan into two batches, but many of the topics relate to each other and it was hard creating research questions for each topic that didn't seem redundant or overlap. We will most likely be gathering a lot of feedback from an interviewee at once that can give us data and insight into designing for each of those stories when we get to it. (It may be that we come up with flows and processes first, then figure out the features and modify our stories)

```gherkin
Feature: Create research plan and research questions for interviews
  As a UX researcher
  I want to create a clear research plan with clear research questions I want answered
  So that I can create interview questions that will get me the data I need

Scenario: Create research questions
    Given that our internal IBM users will be the main user of the WOX CMS
      And that we do not understand their workflows, needs and requirements
     Then I should list out clear research questions that will lead the direction in creating our research plan and interview questions

  Scenario: Craft research plan
    Given that I will have crafted clear and concise research questions
      And that I will be using those questions to guide creation of my research plan
     Then I will create a research plan for each CMS user research topic I am tackling

```

---

**Research Questions/Research Plan**
- [x] Create research questions (Box link: https://ibm.box.com/s/atjdrqa48r42n7chxka8c4m2mrykj0o8)
- [x] Create research plan (Box link: https://ibm.box.com/s/rqla1fhkgsmqtle3w75tz6f6kdkzuj7o)

**Comment by mkiang3051** [comment]
@ineedsubstance 
I was thinking about it and I don't think it makes sense to have one of these stories for every topic we're pursuing, as we're most likely going to be asking the interviewees a bunch of questions at one time pertaining to multiple topics. 

Because of this, I've at least broken it up into two batches (this is the first one) - and we can break up more later (or combine) if needed.

**Comment by mkiang3051** [comment]
@ineedsubstance 
I've created some prelim research questions (which are overarching research questions that will guide our interviews - they are different from interview questions) which we can keep in mind when we craft the actual interview scripts. It's really good we've outlined questions we have/topics within a topic we want answers too - so each story that you/we flesh out will help as well.

**Comment by mkiang3051** [comment]
From Allen (@SirSpidey): Miranda, some thoughts:
• How will we be depicting the workflows (swimlane or flow diagrams?) 
• I know that you explicitly broke the goals out, but I think we need to think about how they are related.
Workflows handle most of the bullets: 
    • The user roles or players (e.g., authors, reviewers, editors, and approvers)
    • The responsibilities (task types, such as work tasks, transport tasks, and wait tasks),
    • The processes (with start and end points and tasks). For ex., approval of beta release of a svc)
    • Alerts/notifications. 
So, you might consider reorganizing the bullets for workflows, navigation, finding content (or is this finding tasks in workflows?), and getting started/getting help.
----
@SirSpidey 
Excellent comments. @ineedsubstance and I had originally started off with breaking out the features/functionality we have/will have in the CMS and then populating it with details/questions around what the type of information we want to get from our users to help us flesh these features out. 
You're right - many of these topics/goals are VERY interrelated - and I found that out yesterday as I was trying to create broad research questions for each topic (I had already split the topic in half based on priority to the CMS in an attempt to better break up research tasks into consumable stories in one sprint) - many of the questions were overlapping/redundant, or directly related. It wasn't easy (and I'm not sure it's the best route) to split the user research/interview stories out so much.

So to answer your questions:
1) I'm thinking of representing the workflows and pain points in a flow diagram - that shows the direction of the work and how each role interacts with the other roles. I also want to clearly mark some pain points, so Nick and I can see if we can help alleviate any of those with some good UX in the CMS.
2) I will revisit my research questions to see if I should just keep all the topics together and formulate the interview portion differently (because I know we won't be talking to users 5-8 times to get feedback on all the separate feature stories we have.)

**Comment by mkiang3051** [comment]
Oh and I forgot to ask: @SirSpidey
Can you clarify what you mean by "finding content" vs "finding tasks"? Can you give me an example of what a task in your workflow may be?
Is it something like: Approver logs into CMS and sees that there are notifications alerting them of new content to review

**Comment by SirSpidey** [comment]
My ideas about finding
* Finding content = for reuse
* Finding tasks = what am I supposed to do next (might apply more to approvers and reviewers than to creators)

There is the another, which you might have meant for finding content: 
* Finding the darn thing I'm trying to revise.

**Comment by SirSpidey** [comment]
@mkiang3051 @ineedsubstance: We might consider "seeding" the workflows and looking for variations and additions. There shouldn't be that many

**Comment by mkiang3051** [comment]
@SirSpidey Awesome - that clears things up a bit relating to how we're talking about "finding."
Would the "finding the darn thing I'm trying to revise" fall into a the "finding content = for reuse"? Or is it related but not the same? Or is it just a totally different idea related to finding?

And also, what does does "seeding" the workflows mean here? I know of seeding a plot of land, or seeding downloads... O_O

**Comment by mkiang3051** [comment]
Updated the docs, but here are the broad, overarching research questions I have:

### Research Questions - Overarching

1. What are the roles present on each of the orgs/teams that will be using the WOX CMS?
2. How do the roles work together/communicate with the other roles on the team? (Where does the work intersect/touch?)
3. What are the team workflows around content creation?
4. And how many distinct workflows are there?
5. What are the current pain points in the whole process? (If any)

**Comment by SirSpidey** [comment]
@mkiang3051: My thoughts re **Seeding**. I just meant that we can come up with some of the workflows to validate so that the research time is not spent re-creating the wheel each time. We don't need to find "the best" workflow, just validate if we have them all.

I would add to your overarching questions:
• What are the phases of the content lifecycle (e.g., Create, Review, Manage, Deliver)

**Comment by mkiang3051** [comment]
@SirSpidey Ahhh ok, yes. Totally makes sense. We "ain't got time" for re-creating wheels to be square instead of circle. 😆 

Good suggestion - I'll add it to my list of overarching research questions!

**Comment by mkiang3051** [comment]
@ineedsubstance 
No rush! But if you have a moment later when you are caught up and can review the research plan and broad research questions, that'd be great! I've edited them a bit per Allen's comments/suggestions. I'm currently in the process of crafting interview questions, so this isn't a blocker or anything.
