### ISSUE TITLE
UX Researcher: Creating User Interview Questions + Interview Script

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#357]
Creating the interview questions that should cover and provide some data for the following research topics:
* User roles + team mgt (#294)
* (Approval) workflows (#296)
* Content creation (#301)
* Editing content (#295)

---

* Content types (understanding/navigating to content types) (#297)
* Alerts + notifications (#300)
* First time experience on the CMS (#341)
* Searching for content (#299)

```gherkin
Feature: Create interview questions + interview script for user interviews
  As a UX researcher
  I want to create a clear research plan with clear research questions I want answered
  So that I can create interview questions that will get me the data I need

  Scenario: Craft interview questions
      Given that I will have created research questions and a research plan
      And that I will be using those assets to guide my interviews
     Then I will create interview questions that will help us gather the data we need to help answer the questions we have about our users

```

---
**Research Interview Questions + Script**
- [x] Create interview questions (https://ibm.box.com/s/i7jpsm9wayrh5t6pzfok7hlzwd1nculq)

**Comment by joshkimmell** [comment]
@mkiang3051: I'm moving this to new stories to discuss at grooming tomorrow.

**Comment by mkiang3051** [comment]
@joshkimmell Ok. I've also moved a couple other stories back to new stories as well.

**Comment by mkiang3051** [comment]
@ineedsubstance 
I added a scenario to this story about crafting an interview script for Jeremy and Allen (it may look very similar, but I may move questions around a bit and we'll learn from interviewing them about what we may need to tweak)

**Comment by mkiang3051** [comment]
I had added the Interview Script scenario to this yesterday but hadn't had time to do it today. I don't foresee the interview scripts for Allen and Jeremy differing too much from my raw list of interview questions... I could potentially close this and just create a new story for the interview scripts for this upcoming sprint.

**Comment by mkiang3051** [comment]
@joshkimmell Feel free to review the interview questions and comment before I go about creating the actual scripts for interviewing Jeremy and Allen
