### ISSUE TITLE
Bug: reference plugin as require

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#364]
References is not available as a `require` when creating multi-input plugins. It works when using within content-types, but when trying to test a multi plugin using it, the `require` statement fails in node.

## Steps for Reproducing

- Create a multi-input plugin using references in an app that uses Punchcard as a module
- Set up the multi-input to use the `shared-tests`
- Run `npm test`
- Error returned: `Error: Error: Input 'method-example-request' not found`

**Comment by scottnath** [comment]
@Snugug I'm opening this bug so that we can figure out the options to fix this and write stories in kind.

The issue is that when we use this in another plugin:
`const reference = require('input-plugin-reference');`
then node hates it and cannot find it and thinks it's dumb.

## Options:

1. Export the plugins inside punchcard and use them something like this:
`const reference = require('punchcard-cms/plugins/input-plugin-reference');

    _problem_: would *only* work when creating a CMS with Punchcard as a module, but would not work for any multi-input plugins which would be distributed via npm

2. Move reference out of punchard so it can be included as an npm module - and no longer put core plugins in Punchcard's repo

    _problem_: Core modules would probably not work as a standalone module on their own - reference certainly does not

**Comment by Snugug** [comment]
May I introduce you to [peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies)

**Comment by scottnath** [comment]
So...you vote `2.` - remove from punchcard repo. Correct?

**Comment by scottnath** [comment]
This will now eat my day manana: https://github.com/punchcard-cms/punchcard/issues/365

**Comment by scottnath** [comment]
option #1 is actually the answer. All fixed, closing this issue.
