### ISSUE TITLE
Bug: Self-Publish Appears To Create Duplicates

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#376]
Publishing a revision of a piece of content with a self-publish workflow results in duplication of content

## Steps for Reproducing

- Create Content Type with a Self-Publish Workflow
- Create a piece of content and save a valid revision
- Edit a valid revision and publish that revision
- Note that there is now a duplicate of that piece of content in the listing of all content

## Screenshots

![screen shot 2016-09-12 at 10 05 05 am](https://cloud.githubusercontent.com/assets/377188/18438695/6d2914e2-78d0-11e6-98fa-d1b4bc7acf77.png)

## Affected Browsers

- [ ] All

## Runtime Version

5.11

## Code Version

2.10.0

**Comment by scottnath** [comment]
@Snugug is it the `English (UK)` one that is the duplicate?

**Comment by Snugug** [comment]
All of them have duplicates.

**Comment by scottnath** [comment]
ok. This is a weird one because there is only one `insert` line in `save`.

Are you going to tackle this today?

**Comment by Snugug** [comment]
No, I've got other work I need to do through the end of this sprint. I'm filing a few bugs, these should be prioritized at the top of next sprint
