### ISSUE TITLE
Revision Editing Takes A Long Time

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#382]
Revision Editing appears to be taking about 1500ms to actually get rolling. We should figure out how to increase performance for it.

```gherkin
Feature: {{feature}}
  As a {{persona}}
  I want {{need}}
  So that {{rationale}}

  Scenario: {{scenario}}
    Given {{thing}}
     When {{action}}
     Then {{result}}
```

---

**{{feature}}**
- [ ] {{scenario}}

**Comment by scottnath** [comment]
superseded by the EPIC epic
