### ISSUE TITLE
UX Researcher: Creating Interview Script - Batch 1: Roles and Team Needs

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#401]
I am going to modify my base interview questions and scope them down to create an interview script for the interviews with our primary users: Jeremy and Allen.
This portion of the interview script will focus on user roles and team needs. #294 

```gherkin
Feature: Create interview script for user interviews with Jeremy and Allen
  As a UX researcher
  I want to create an interview script from my list of interview questions crafted for the CMS UX that is catered to the role of the specific interviewee around understanding their team roles and needs
  So that I can make sure to ask the interviewee specific questions that will be relevant to their role and their team

 Scenario: Craft interview script for Jeremy
    Given that Jeremy will be the main user entering marketing content into our CMS
     When I go to craft his interview script centered around his role and this team needs
     Then I will be able to ask Jeremy the questions that will allow me to gather data to understand the marketing team structure
      And his role
      And the roles present on the team
      And the ways roles report to and interact with each other
      And the type of work that each role does
      And the way the team communicates with each other
      And the teams' needs / expectations from using a CMS

Scenario: Craft interview script for Allen
    Given that Allen will be the main user entering ID content into our CMS
     When I go to craft his interview script centered around his role and this team needs
     Then I will be able to ask Allen the questions that will allow me to gather data to understand the ID team structure
      And his role
      And the roles present on the team
      And the ways roles report to and interact with each other
      And the type of work that each role does
      And the way the team communicates with each other
      And the teams' needs / expectations from using a CMS
```
---
**Research Interview Script**
- [x] Create interview script for Allen around understanding roles and team needs
- [x] Create interview script for Jeremy around understanding roles and team needs

**Comment by mkiang3051** [comment]
* User roles + team mgt (#294)
* (Approval) workflows (#296)
* Content creation (#301)
* Editing content (#295)

---

* Content types (understanding/navigating to content types) (#297)
* Alerts + notifications (#300)
* First time experience on the CMS (#341)
* Searching for content (#299)

**Comment by mkiang3051** [comment]
@ineedsubstance @joshkimmell @poofichu @Snugug @scottnath @SirSpidey 

Rewrote this story as well and scoped it to a research topic and added it to that specific epic. Let me know your thoughts and if this story makes sense.
If you review this one and #397 they are very similar - except this one is centered around the interview script I will be using in my interview.

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think this is good and clear. I would suggest adding this as a `blocker` to #397 as this needs to be done first before the actual interview.

**Comment by mkiang3051** [comment]
@ineedsubstance Thanks for reviewing! And good suggestion. I'll add the blocker marker.

**Comment by mkiang3051** [comment]
As @ineedsubstance stated, this is a blocker for #397

**Comment by mkiang3051** [comment]
Link to interview script on Box: https://ibm.box.com/s/3qcrna0siatds3c9lme34ebm6k1i1yad

**Comment by joshkimmell** [comment]
This is done.
