### ISSUE TITLE
Content Creator: Visual affordance implementation

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#404]
Allow users to be able to identify the fields that are required to save and those that are required to published.

```gherkin
Feature: Visual affordance for required fields
  As a Content Creator,
  I want to be able to identify which fields are required
  So that I know what fields are required when creating and editing content.

  Scenario: Required for saving
    Given I will need to gather content to enter into the CMS
      And that certain content is required for the content to be eligible to save
     When I look to create or edit content
     Then I will see a visual affordance for required fields
       And identify which fields I need to complete to save

  Scenario: Required for publishing
    Given I will need to gather content to enter on the CMS
      And that certain content is required for the content to be eligible to publish
     When I look to create or edit content
     Then I will see a visual affordance for required fields
       And identify which fields I need to complete to publish
```

---
**Visual affordance for required fields:**
- [x] Required for saving
- [x] Required for publishing

---

Reference #336

**Comment by ineedsubstance** [comment]
**v1 - color bar on left side of input + required text highlight**

![desktop-form-v1](https://cloud.githubusercontent.com/assets/3981381/18443560/091dc316-78db-11e6-919e-7a6ddb0865a4.png)

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu @mkiang3051 @scottnath - This story relates to #336, and is the implementation of the UX work I did. Consumable?

**Comment by scottnath** [comment]
@ineedsubstance totally consumable 
For dev this is a 3, partly because it will touch two repos.

**Comment by mkiang3051** [comment]
@ineedsubstance It looks consumable to me! 👍 
The only part that was throwing me off a little bit was what you mean by `expected` in the feature:  `So that I know what is expected when creating and editing content.`

**Comment by poofichu** [comment]
Visual design wise, I would give this a 3 as well.  There is some risk involved in cross-browser compatibility with this, but overall not to heavy.

**Comment by ineedsubstance** [comment]
Good call @mkiang3051, updated that to `fields are required`.

@scottnath - from what I have seen, it will touch more repos than that (punchcard for styling and any input plugin (text, textarea, select, etc.) that might need this update. Is that correct, or am I thinking about this all wrong?

**Comment by ineedsubstance** [comment]
@scottnath - Correct me if I'm wrong, but I will need to add the "required to save/publish" text and logic to every input-plugin individually, right?

https://github.com/punchcard-cms

**Comment by scottnath** [comment]
Nope, we can just make this part of the Punchcard Content-Types form-building system

**Comment by ineedsubstance** [comment]
@scottnath - hmm... might need help with that. Where does that live?

**Comment by ineedsubstance** [comment]
@scottnath - I think I'm missing something, but it looks like each input-plugin has the field HTML (label + input) included with each plugin. Example [here](https://github.com/punchcard-cms/punchcard/blob/master/input-plugins/input-plugin-reference/index.js#L38).

My solution thus far was to add a conditional statement to the `<label>` on each to add the required to ... text depending on if the field was required to save or publish.

```
<label for="{{reference.id}}">{{reference.label}} {% if reference.required == "save" %}<mark class="mark-save">required to save</mark>{% endif %}{% if reference.required == "publish" %}<mark class="mark-publish">required to publish</mark>{% endif %}</label>
```

It looks like `/views/content/_form-content.html` builds the form pages, so it that where the label change code should go?

**Comment by ineedsubstance** [comment]
@joshkimmell @mkiang3051 - @poofichu and I took a look at the visual styling on this, and some of the issues that were happening with adding a border within the input or adding a border to the left of the field and decided to remove for now. What remains is the `required to save/publish` text with a text highlight color designated for each.

**Color indicator within input: (because top & bottom borders are white, the left border get's cut off)**

![screen shot 2016-09-20 at 1 30 08 pm](https://cloud.githubusercontent.com/assets/3981381/18683798/5bb906fa-7f37-11e6-9125-31d634c9c43f.png)

**Color bar outside of field: (add's too much visual noise, especially when dealing with fieldsets)**

![screen shot 2016-09-16 at 4 08 41 pm](https://cloud.githubusercontent.com/assets/3981381/18683781/4fc9c0e6-7f37-11e6-99c6-2f8ebb62d738.png)

**Required text only with the highlight: (is enough of a visual indicator for now. we can revisit if we test and users are still having issues)**

![screen shot 2016-09-20 at 1 24 57 pm](https://cloud.githubusercontent.com/assets/3981381/18683810/681467e6-7f37-11e6-8314-663dbeb655be.png)

**Comment by mkiang3051** [comment]
Ok, that's fine - we don't want to spend too much time on this at the moment since we have so much else to do! I think having the text highlighted works for now. A bit of sadness though. 😿  

What was good about having some sort of indicator on the text box itself is that the eye can easily see what text box the highlighted text refers to visually without having to think too much or having ones eyes get lost from staring at too many boxes. It's easier to scan and see color on the text box to know that text box needs something input, vs. seeing text highlighted and then taking a millisecond to look down to see what box that highlighted text is referring to. 

I am happy to help out and revisit this too, if users are having issues.

**Comment by joshkimmell** [comment]
I agree, as long as we don't use teal. There's not enough contrast from the background.

**Comment by ineedsubstance** [comment]
@poofichu ^^ any thoughts on what we would use if we didn't use `teal` for one of the colors? Could either the `blue` or `green` work?

**Comment by joshkimmell** [comment]
@ineedsubstance To get this done, the green from above is fine. We can change it later if we don't like it.

**Comment by poofichu** [comment]
@joshkimmell we're already there with not liking the green.

To keep with the color palette we have (teal and purple) I think would be wise.  The teal contrasts a great deal for me.  Are you saying it's competing with the teal border?  If that's the case, we can easily change that color.

**Comment by joshkimmell** [comment]
@poofichu I disagree about the contrast, but sure, let's move forward.

**Comment by scottnath** [comment]
@ineedsubstance re: "add a conditional statement to the <label>"

For *all* input plugins, we have to stay away from changing the html for Punchcard UX purposes as we have no way to control the html for any plugins not created by us. So, solutions like adding text for error/required must be done when the plugin is processed.

So...what we already do when we have elements which need classes to denote `required` (both save and publish), is read the html and add/update the class attribute on label. We can use this processing step to add whatever text/html you feel is needed.

**Comment by ineedsubstance** [comment]
@scottnath - OK, that makes sense. Thanks for the explanation.

**Comment by ineedsubstance** [comment]
@scottnath - took a stab at this here: https://github.com/punchcard-cms/content-types/pull/111

**Comment by ineedsubstance** [comment]
PR was updated on Friday, waiting on feedback.
