### ISSUE TITLE
UX Researcher: Creating Interview Script - Batch 1: Content Creation

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#416]
#I am going to modify my base interview questions and scope them down to create an interview script for the interviews with our primary users: Jeremy and Allen.
This portion of the interview script will focus on team needs around creating new content. #301 

```gherkin
Feature: Create interview script for user interviews with Jeremy and Allen
  As a UX researcher
  I want to create an interview script from my list of interview questions crafted for the CMS UX that is catered to the role of the specific interviewee around understanding their team needs around creating new content
  So that I can make sure to ask the interviewee specific questions that will be relevant to their role and their team

 Scenario: Craft interview script for Jeremy
    Given that Jeremy will be the main user entering marketing content into our CMS
     When I go to craft his interview script centered around understanding his team's needs around creating new content
     Then I will be able to ask Jeremy the questions that will allow me to gather data to understand the marketing team's needs around creating new content, which includes finding the input type to start with
      And the minimum amount of content required to save
      And the minimum amount of content required to publish
      And the ability to preview a piece of content
      And the steps to take to push a piece of content to the next stage in the workflow
      And the definition of "done" for a new piece of content
      And the needs around how saving a revision works
      And understanding where they get content from, how it's collected and when they receive it in the process
      And understanding the cadence from creating to publishing a piece of content (time spent, amount of edits, amount of back and forth)
     
Scenario: Craft interview script for Allen
    Given that Allen will be the main user entering ID content into our CMS
     When I go to craft his interview script centered around understanding his team's needs around creating new content
    Then I will be able to ask Allen the questions that will allow me to gather data to understand the ID team's needs around creating new content, which includes finding the input type to start with
      And the minimum amount of content required to save
      And the minimum amount of content required to publish
      And the ability to preview a piece of content
      And the steps to take to push a piece of content to the next stage in the workflow
      And the definition of "done" for a new piece of content
      And the needs around how saving a revision works
      And understanding where they get content from, how it's collected and when they receive it in the process
      And understanding the cadence from creating to publishing a piece of content (time spent, amount of edits, amount of back and forth)
```
---
**Research Interview Script**
- [ ] Create interview script for Allen around marketing team's needs for creating new content
- [ ] Create interview script for Jeremy around ID team's needs for creating new content

**Comment by mkiang3051** [comment]
Blocker for #417

**Comment by mkiang3051** [comment]
@ineedsubstance @joshkimmell @poofichu @Snugug @scottnath @SirSpidey

And another interview script story...

**Comment by ineedsubstance** [comment]
@mkiang3051 - What I might add. It possible this makes more sense on the `Edit` or `Workflow` stories, but I'll let you make that call.

```gherkin
And understand where they get content from, how it's collected and when they receive it in the process
And understand the cadence from creating to publishing a piece of content (time spent, amount of edits, amount of back and forth)
```

**Comment by mkiang3051** [comment]
@ineedsubstance 
Thanks!! These are good - I think it makes more sense under workflow, so I'll add it to that one. It's tough because many of these stories are so inter-related; it's sometimes hard to pull out certain pieces of information for one story. But workflow can be kind of our unifying larger picture view of the workflow, while the content creation and editing stories can focus more on the scope of that portion of the workflow? (I don't know if I am making sense... I think my brain is dying...)

To be short: I'll add it to the workflow one for now, and if we decide we want it to be in the content creation and editing content stories, we can add it later.

**Comment by ineedsubstance** [comment]
@mkiang3051 - I don't think it's bad to add something to both stories if it makes sense especially since there could be overlap on these type of stories.

**Comment by mkiang3051** [comment]
@ineedsubstance 
Ok - it won't hurt to have in related stories, since it's relevant. 

Added to this story and the editing existing content stories as well as having it reside in our workflow stories:
#414 
#415 
#416
#417 
#418 
#419

**Comment by mkiang3051** [comment]
Link to interview script on Box: https://ibm.box.com/s/3qcrna0siatds3c9lme34ebm6k1i1yad

**Comment by joshkimmell** [comment]
This is done.
