### ISSUE TITLE
UX Researcher: Synthesizing CMS User Interviews - Batch 1: Alerts and notifications

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#438]
Synthesize CMS user interview notes/data with primary users, Jeremy (marketing) and Allen (ID) about user needs for alerts and notifications #300 

```gherkin
Feature: Synthesizing interview data
  As a UX researcher
  I want to synthesize the data collected from the user interviews 
  So that I can see what questions about user roles and team needs for the CMS have been answered and what information I still need to attain from future interviews

  Scenario: Review and clean up raw interview notes
    Given that I will have collected data from my interviews in various forms (video/audio recording and handwritten notes) and in various levels of legibility and consumability
     When I go to review and clean up my raw interview notes
     Then I will be sure that everything is legible and that sentences are and ideas are fully formed so I can create a second round of cleaner, better organized notes from the raw notes

  Scenario: Create better organized interview notes
    Given that I will have reviewed my raw interview notes to make sure that it is legible and contains fully formed sentences and ideas
     When I go create cleaner and better organized notes from my raw notes
     Then I will be able to use these cleaner notes as a basis for creating assets around defining the main insights and findings from the CMS user interviews for my teammates to read and review

  Scenario: List out main insights and findings from user interviews
    Given that I will have created clean and organized interview notes that are easy to consume
     When I go to use my notes to pull out the main insights and findings from my interviews
     Then I will be able to list out my main insights and findings from my user interviews
      And be able to communicate these main insights and findings to the broader team
      And use this information in any research assets that I may create later on

  Scenario: Create wiki page of insights and findings on our GitHub (CMS) Wiki
    Given that I will have listed out the main insights and findings from the user interviews
     When I go to create a wiki page featuring our main insights and findings on our GitHub (CMS) Wiki 
     Then I will be able reference the notes in an easily accessible location on the CMS Wiki in my web browser
      And be able to send the link out to my teammates
      And be able to send the link to those who may be interested in my research that aren't on my direct team

  Scenario: Upload data and notes to WOX Box folder for reference
    Given that I will have created many research assets in various levels of fidelity
     When I go to upload all these assets onto my WOX Box research folder
     Then I will be able to have a backed up and consolidated location to access all my raw notes
      And my cleaned up notes
      And my main insights/findings
      And any raw audio/video files
      And any presentation slides
      And any additional related research/UX assets

```

---

**Synthesizing Interview Data**
- [x] Review and clean up raw interview notes
- [x] Create better organized interview notes from the raw notes
- [x] List out main insights and findings from the user interviews
- [x] Create Wiki page with main insights and findings (in CMS wiki: https://github.ibm.com/Watson/wox-cms/wiki/CMS-User-Interview-Notes---Organized-by-GHE-Issues-Topics)
- [x] Upload data and notes to WOX Box folder (see links below)

---

**Box files/notes:**
- [ ] Jeremy combined notes (https://ibm.box.com/s/wzerbtsxdu9p0jwj3fgmvozz4ooxcjiq)
- [ ] Allen combined notes (https://ibm.box.com/s/qh2ss5qo2ra95zos8x0urbdpylszcdqm)
- [ ] Combined notes from 1st round interviews sorted by issues/topics: (https://ibm.box.com/s/a7t62sysfme5mjjn2u0p7ooxy5j724lz)

```

**Comment by ineedsubstance** [comment]
@mkiang3051 - Do you think synthesizing is only about finding those information gaps, or does this include the analysis and recommendations? Or is that another story?

**Comment by mkiang3051** [comment]
@ineedsubstance I think mostly about information gaps and also insights/findings if we can make them. These stories, for the moment, are just for consolidating and cleaning up the notes we have, finding the gaps, and publishing some tentative insights. 
I think I may need to make a few more of these stories for other users we interview and then a combined research story for a more comprehensive analysis with recommendations after we get to interviewing more folks from both teams.

**Comment by ineedsubstance** [comment]
@mkiang3051 - OK, makes sense. I do think there needs to be a story or stories around what we do with this information and how it informs the CMS moving forward.

**Comment by mkiang3051** [comment]
Yup there will be. I'm not getting ahead of myself yet with that since I haven't even had a chance to dig through the wealth of information from Jeremy and Allen's interviews. :D

**Comment by ineedsubstance** [comment]
Sounds good

**Comment by joshkimmell** [comment]
👍 Looks good to me.

**Comment by mkiang3051** [comment]
@joshkimmell @ineedsubstance Thanks! Can I move this (and my other related research synthesis stories over into backlog)?

**Comment by joshkimmell** [comment]
@mkiang3051 So... I think the sizing should be a little higher than 2. 2 is just above `mindless` work. This is going to take some critical thinking, so I'd estimate it at least a 5.

**Comment by mkiang3051** [comment]
@joshkimmell Yep - I agree it's not mindless work. It definitely IS tasking! So I agree, if I had a single synthesis story, it'd be at least a 5.
The only issue with that is, I have several synthesis stories that are interrelated because I've created a separate story for each research topic. So I could be synthesizing data that affects 5-6  stories at once (each covering a different research topic) - so if they're all a 5 each, it'd put me way over capacity for a sprint, even if I started out at nothing. :/
(research story woes...)

**Comment by joshkimmell** [comment]
Don't worry about that. If you finish one, you can move to the next until you're done.

**Comment by mkiang3051** [comment]
@joshkimmell Sounds good. I'll size it as a 5 and move this (and the other related stories) to the backlog. I'll move them over to In Progress as I tackle them.

**Comment by joshkimmell** [comment]
I moved this into the sprint and assigned to you. For the others like this, if they are estimated at 5, go ahead and move them to the backlog. As you finish one, please ask @ wox in Slack if it's okay to move the next one into the sprint.

**Comment by mkiang3051** [comment]
@joshkimmell I have gotten the data for this from my first round of research. I may need to follow up with our users later to get more details about this topic - but I am going to close this issue. 
I will create additional research issues in the future.
