### ISSUE TITLE
Bug: Repeatable inside of input plugin isn't working

### ISSUE THREAD

**Issue by joshkimmell** [punchcard-cms/punchcard#446]
Repeatable inside of a repeated input plugin is not itself repeatable

## Steps for Reproducing

- Create an input plugin with a reference
- Use that plugin in a content type and set both the plugin and the reference to `repeatable: true`
- Note that only the parent plugin is repeatable

## Screenshots
<img width="420" alt="screen shot 2016-09-22 at 4 00 22 pm" src="https://cloud.githubusercontent.com/assets/8161298/18766073/1a44898a-80de-11e6-824b-678f3a0dc77d.png">

![image](https://cloud.githubusercontent.com/assets/8161298/18766087/2a34ca30-80de-11e6-9549-f6f6bd50da20.png)

## Affected Browsers

- [ ] All

## Runtime Version

5.11

## Code Version

2.10.0

**Comment by scottnath** [comment]
adding a 2 for researching this bug. Once research complete, a new story for fixing it will need to be created.

**Comment by scottnath** [comment]
This bug was fixed in `content-types` in this PR:
https://github.com/punchcard-cms/content-types/pull/132
