### ISSUE TITLE
Bug: Routing: there is a too-open search for `add` to change to `save`

### ISSUE THREAD

**Issue by joshkimmell** [punchcard-cms/punchcard#447]
If a content type contains the word `add`, the routing attempts to replace it with the word `save`

## Steps for Reproducing

- Create a content type with the word `add` in the name, like `add-on`
- Attempt to save an `add-on` in the CMS
- Note that it results in a 404 page because it can't find the content type `save-on`

## Screenshots
![image](https://cloud.githubusercontent.com/assets/8161298/18798280/57d093b6-8197-11e6-9d46-bff1e4056210.png)

## Affected Browsers

- [ ] All

## Runtime Version

5.11

## Code Version

2.10.0
---

**Comment by joshkimmell** [comment]
@Snugug @scottnath 
This is a significant bug and should be prioritized. Since this is open-source, we cannot control how users name content types, so just changing `add` to `save` is a problem.

**Comment by Snugug** [comment]
Sized and added based on convo with @scottnath
