### ISSUE TITLE
Reference Input Plugin

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#45]
Need an input plugin for referencing one piece of content (with fields) from another.

```gherkin
Feature: Reference Content
     As a Content Creator
     I want to reference one piece of content from another
     So that those pieces of content can be considered together

  Scenario: Reference
    Given that I want to reference content-type A while writing content in content-type B
     When I am writing a piece of content in content-type B
     Then I can reference a piece of content in content type A by selecting it from a list
      And that list can either be a select box or radio buttons
      And the content is represented by its `identifier` attribute of the latest revision
      And the content is referenced by its UUID
```

---
**Reference Content**
- [ ] Reference

**Comment by Snugug** [comment]
Thoughts on solution:

- Going to want to be able to distribute with Punchcard so we can have direct DB queries. Will need to update Plugabilly or Content Types to support this
- Going to want a `join` table to be able to quickly index and search via `foreign keys`
- Do we want this to include revisions? I think it's _important_, but maybe not _needed_
- Need 2 way binding

**Comment by scottnath** [comment]
![20160722-reference-white-board](https://cloud.githubusercontent.com/assets/216931/17117309/93fdb784-5289-11e6-998d-1a6ae8cd93ad.jpg)

**Comment by scottnath** [comment]
![20160722-reference-white-board](https://cloud.githubusercontent.com/assets/216931/17117345/b8a41308-5289-11e6-929b-6f62537865ec.jpg)

**Comment by Snugug** [comment]
So, more thoughts on this, now that the whiteboarding is up:

* Original thoughts may not be correct with new API implementation
* May want to configure a generic plugin that takes a generic or controlled set of endpoints with display and save options
* May want to distribute with Punchcard, may not

**Comment by ayush2k** [comment]
@scottnath Does this change the current story?

**Comment by ineedsubstance** [comment]
@scottnath - adding this here to put it on your radar.

Just realized when we reference some content types, like taxonomy and API for example, we will need the ability select more than one of that content type. So basically a multi-select for a reference.

**Comment by Snugug** [comment]
And we have decided we no longer want to do field reference. I think this issue needs to be rewritten based on the whiteboarding

**Comment by scottnath** [comment]
totally. Ayush is starting writing the stories today. Just had an hour planning meeting. He'll be writing stories that we can then go over when you're back next week.

**Comment by Snugug** [comment]
This is in this sprint, but doesn't have an estimate. What did we estimate this as?

**Comment by scottnath** [comment]
@Snugug not sure, Ayush did the work :/

**Comment by Snugug** [comment]
Let us please make sure that work isn't started until we have an estimate in
