### ISSUE TITLE
Bug: schedule tests failing

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#468]
Push and Pull are still failing after a `git pull upstream master`

## Steps for Reproducing

- run tests `npm test`
- See error:
```
Sunset failed: undefined
Sunrise failed: undefined
undefined

  schedule › Push
    ⨯ schedule › Push

      Expected false but got false

      At: schedule.js:57:7
```

## Screenshots

<img width="299" alt="screen shot 2016-09-30 at 6 19 43 pm" src="https://cloud.githubusercontent.com/assets/216931/19008639/8d1490ba-873a-11e6-8dea-c785f239f7db.png">

**Comment by Snugug** [comment]
I'm unable to reproduce this, and it is not reproduced [on travis](https://travis-ci.org/punchcard-cms/punchcard/builds/164173234#L455-L469)

**Comment by scottnath** [comment]
Closing. Looks like this was fixed with a fresh `npm install`

**Comment by scottnath** [comment]
@Snugug it's baaaaaaaaack

**Comment by scottnath** [comment]
and it's gone...user error...user=scottnath...scottnath error
