### ISSUE TITLE
Update to Node 6

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#487]
All of Punchcard and its sub-modules should be updated to Node 6 [by October 18th](https://github.com/nodejs/LTS) as that will become the current Long-Term Support version of Node

```gherkin
Feature: Node LTS
  As a Core Developer
  I want to use the latest long-term support version of Node
  So that I receive security and feature updates to my runtime and still use Punchcard

  Scenario: Compatibility
    Given that I have Punchcard downloaded
     When I go to install Punchcard
     Then all of Punchcard's dependencies will be use-able with the latest long-term support version of Node

  Scenario: Run
    Given that I have Punchcard installed
     When I go to run Punchcard
     Then it will expect the latest long-term support version of Node
      And it will work with the latest long-term support version of Node
```

---

**Node LTS**
- [x] Compatibility
- [x] Run

---
**List of Punchcard modules that need to be updated**
- [x] [Punchcard](https://github.com/punchcard-cms/punchcard) - **https://github.com/punchcard-cms/punchcard/pull/493**
- [x] [Content Types](https://github.com/punchcard-cms/content-types) - **https://github.com/punchcard-cms/content-types/pull/128**
- [x] [Runner](https://github.com/punchcard-cms/runner) - **https://github.com/punchcard-cms/runner/pull/54**
- [x] [ESLint Config Punchcard](https://github.com/punchcard-cms/eslint-config-punchcard) - **https://github.com/punchcard-cms/eslint-config-punchcard/pull/20**
- [x] [Shared Tests](https://github.com/punchcard-cms/shared-tests) - **https://github.com/punchcard-cms/shared-tests/pull/14**
- [x] [Semantic Release](https://github.com/punchcard-cms/semantic-release) - **https://github.com/punchcard-cms/semantic-release/pull/18**
- [x] [Commit Msg](https://github.com/punchcard-cms/commit-msg) - **https://github.com/punchcard-cms/commit-msg/pull/18**
- [x] [OptiCache](https://github.com/punchcard-cms/opticache) - **https://github.com/punchcard-cms/opticache/pull/7**
- [x] [Input Plugin Boolean](https://github.com/punchcard-cms/input-plugin-boolean) - **https://github.com/punchcard-cms/input-plugin-boolean/pull/71**
- [x] [Input Plugin Checkbox](https://github.com/punchcard-cms/input-plugin-checkbox) - **https://github.com/punchcard-cms/input-plugin-checkbox/pull/30**
- [x] [Input Plugin Currency](https://github.com/punchcard-cms/input-plugin-currency) - **https://github.com/punchcard-cms/input-plugin-currency/pull/11**
- [x] [Input Plugin Date](https://github.com/punchcard-cms/input-plugin-date) - **https://github.com/punchcard-cms/input-plugin-date/pull/52**
- [x] [Input Plugin Datetime](https://github.com/punchcard-cms/input-plugin-datetime) - **https://github.com/punchcard-cms/input-plugin-datetime/pull/50**
- [x] [Input Plugin Email](https://github.com/punchcard-cms/input-plugin-email) - **https://github.com/punchcard-cms/input-plugin-email/pull/49**
- [x] [Input Plugin Month](https://github.com/punchcard-cms/input-plugin-month) - **https://github.com/punchcard-cms/input-plugin-month/pull/50**
- [x] [Input Plugin Number](https://github.com/punchcard-cms/input-plugin-number) - **https://github.com/punchcard-cms/input-plugin-number/pull/60**
- [x] [Input Plugin Password](https://github.com/punchcard-cms/input-plugin-password) - **https://github.com/punchcard-cms/input-plugin-password/pull/49**
- [x] [Input Plugin Quote](https://github.com/punchcard-cms/input-plugin-quote) - **https://github.com/punchcard-cms/input-plugin-quote/pull/44**
- [x] [Input Plugin Radio](https://github.com/punchcard-cms/input-plugin-radio) - **https://github.com/punchcard-cms/input-plugin-radio/pull/19**
- [x] [Input Plugin Range](https://github.com/punchcard-cms/input-plugin-range) - **https://github.com/punchcard-cms/input-plugin-range/pull/51**
- [x] [Input Plugin Select](https://github.com/punchcard-cms/input-plugin-select) - **https://github.com/punchcard-cms/input-plugin-select/pull/26**
- [x] [Input Plugin Selects Related](https://github.com/punchcard-cms/input-plugin-selects-related) - **https://github.com/punchcard-cms/input-plugin-selects-related/pull/21**
- [x] [Input Plugin Telephone](https://github.com/punchcard-cms/input-plugin-telephone) - **https://github.com/punchcard-cms/input-plugin-telephone/pull/55**
- [x] [Input Plugin Text](https://github.com/punchcard-cms/input-plugin-text) - **https://github.com/punchcard-cms/input-plugin-text/pull/51**
- [x] [Input Plugin Textarea](https://github.com/punchcard-cms/input-plugin-textarea) - **https://github.com/punchcard-cms/input-plugin-textarea/pull/46**
- [x] [Input Plugin Textarea Limited](https://github.com/punchcard-cms/input-plugin-textarea-limited) - **https://github.com/punchcard-cms/input-plugin-textarea-limited/pull/51**
- [x] [Input Plugin Time](https://github.com/punchcard-cms/input-plugin-time) - **https://github.com/punchcard-cms/input-plugin-time/pull/50**
- [x] [Input Plugin URL](https://github.com/punchcard-cms/input-plugin-url) - **https://github.com/punchcard-cms/input-plugin-url/pull/52**
- [x] [Input Plugin Year](https://github.com/punchcard-cms/input-plugin-year) - **https://github.com/punchcard-cms/input-plugin-year/pull/20**
- [x] ~~[Plugabilly](https://github.com/punchcard-cms/plugabilly)~~
- [x] ~~[Request](https://github.com/punchcard-cms/request)~~
- [x] ~~[Input Plugin Date Range](https://github.com/punchcard-cms/input-plugin-date-range)~~ (empty, should delete)
- [x] ~~[Input Plugin Image](https://github.com/punchcard-cms/input-plugin-image)~~ (empty, should delete)
- [x] ~~[Input Plugin Textarea Feedback](https://github.com/punchcard-cms/input-plugin-textarea-feedback)~~ (empty, should delete)

**Comment by scottnath** [comment]
all good
all done
all day
