### ISSUE TITLE
Kill database connection upon startup error

### ISSUE THREAD

**Issue by rachelnicole** [punchcard-cms/punchcard#51]
When running `npm run dev` if you have an error on startup (I was using the wrong node version for example), it fails to kill the postgres connection, causing any subsequent attempts to start to also fail due to existing connection. You have to manually kill the database connection via `ps aux | grep postgres` and killing the PID.

[

```gherkin
Feature: Kill database connection on startup error
  As a developer
  I want the database connection to be terminated upon startup error
  So that I don't have to manually kill the connection via process id's.

  Scenario: Starting up punchcard, there is an error somewhere
    Given linting error
    When starting up punchcard
    Then the database connection is still started, and any subsequent requests to run `npm run dev` to start punchcard will fail
```

---

**Comment by Snugug** [comment]
Postgres should be sad, but it should not prevent your entire site from starting up.

**Comment by rachelnicole** [comment]
@snugug I'll double check what was going on when I get back, the local host wasn't starting up for me

**Comment by rachelnicole** [comment]
@Snugug confirmed it was my own issue, had to rebuild some libraries. Closing!
