### ISSUE TITLE
Bug: Placeholder Text Bolded

### ISSUE THREAD

**Issue by poofichu** [punchcard-cms/punchcard#557]
The placeholder text is bolded when a label has received a mark (`required to publish`) vs. when it has not.

![image](https://cloud.githubusercontent.com/assets/6757613/20325705/67e74e6a-ab4b-11e6-83b7-0d4ecef3ec4c.png)

**Comment by ineedsubstance** [comment]
Looks like the input is wrapped in the label now. 😕 

<img width="666" alt="screen shot 2016-11-16 at 2 20 13 pm" src="https://cloud.githubusercontent.com/assets/3981381/20364187/cfdb6706-ac07-11e6-9f30-94835c5ba50e.png">
