### ISSUE TITLE
Save and Retrieve Files

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/punchcard#588]
Given that [Pluggable Storage exists](https://github.com/punchcard-cms/punchcard/issues/492), it now needs to be connected to the form

```gherkin
Feature: Files in Forms
  As a Content Creator
  I want to add a file to my content and have it saved
  So that I can have that file available with my content

  Scenario: Save
    Given that I have uploaded one or more files as part of a piece of content
      And the file uploaded meets all validation criteria
     When I save that content revision
     Then the files should be saved using the configured pluggable storage
      And those files should include its file type, original file name, and new, relative file name

  Scenario: Edit
    Given that I have a content revision that includes files
     When I edit that revision
     Then the revision's files should be viewable to me in the form
      And I should be able to edit, add (where appropriate), and remove (where appropriate) the files
      And any files that I have not edited should be available in the revision being edited when saved
```

---

**Files in Forms**
- [x] Save
- [ ] Edit

**Comment by scottnath** [comment]
@Snugug looks like the validation on input-plugin-file is not ready to validate against actual file data that would happen in a real scenario. Added a [bug report in input-plugin-file](https://github.com/punchcard-cms/input-plugin-file/issues/8) and feel said bug should be cleared before I can move forward on the validation scenario.

**Comment by scottnath** [comment]
moved validating of files to a separate story: https://github.com/punchcard-cms/punchcard/issues/603
