### ISSUE TITLE
Developer: Consistent Class Structure

### ISSUE THREAD

**Issue by rachelnicole** [punchcard-cms/punchcard#81]
_As a_ developer _I want_ a consistent class structure _so that_ styling elements is easier

```gherkin
Feature: Consistent class naming & styling
  As a dev
  I want a semantic class naming structure
  So that styling elements is easy and quick

  Scenario: a developer needs to style a page
    Given a good naming structure
    When a dev needs to target specific classes
    Then the process will be more organized and faster
```

---
global header
- [x] logo
- [x] navigation

global footer
- [x] what even goes here

login page
- [x] logged out header
- [x] login form

landing page after login
- [x] landing page content area

content type landing
- [x] list of all content types with links to items

content type list page
- [x] link to add content
- [x] heading title of content type name
- [ ] table of data of all of the content added for that type

add content type page
- [x] heading title of content type
- [x] form ( need to account for all input types ) 

users landing page
- [x] heading for users
- [x] link to add user
- [x] table of users

add users page
- [x] heading title for users
- [x] form ( need to account for all input types )

**Comment by rachelnicole** [comment]
@poofichu @scottnath I've grouped all these checkboxes so they're with the pages they belong to. We need to decide how granular our class naming will be. ie. `base--styled` on a wrapper class, or down further. Also how many of these specific styling elements do we need?

**Comment by Snugug** [comment]
@rachelnicole Please fix the title of this issue

**Comment by rachelnicole** [comment]
lol oops
