### ISSUE TITLE
Core Developer: GitHub repository setup instructions

### ISSUE THREAD

**Issue by scottnath** [punchcard-cms/punchcard#99]
We need a detailed breakdown of how to set up a github repository for a node module which will conform to our CI and semver release processes.

```gherkin
Feature: Instructions on setting up node modules and github repositories
  As a core developer
  I want instructions on setting up new code
  So that all our code is integrated into our massive, yet effective, CI and release process.

  Scenario: Settin' up a github repo
    Given that I am setting up a new github repository
     And that the code in that repository needs to go through our CI process
    When I am setting up the new github repo
    Then I will read the instructions
      And I will have CI working
      And I will have semver release auto-releasing
      And I will talk about all I have learned at parties and family get togethers.

  Scenario: Settin' up a node module
    Given that I am setting up a cool node module
      And that module will need to follow our CI/release process
    When I am setting up this award-winning, world-changing module
    Then I will read the instructions
      And I will set up the things
      And I will do it right
      And I expect I'll have to sign into some stuff
      And all this will lead to profit profit profit.
```

---

- [x] instructurinos / github
- [x] instructurinos / node

**Comment by Snugug** [comment]
- Set up an awesome new Node module using `npm init`
  - Make sure `punchcard-cms` is a keyword
  - Make sure license is `Apache-2.0`
  - Make sure an `https` URL is used for the `repository` field
  - Make sure that `main` is set to `index.js`
- Make a `.github` folder
  - Add templates from [Punchcard](https://github.com/punchcard-cms/punchcard/tree/master/.github)
  - Add a `CONTRIBUTING.md` file whose contents mimc the [Punchcard Content Types](https://raw.githubusercontent.com/punchcard-cms/content-types/master/CONTRIBUTING.md) contributing file
- Add Git Hooks to follow our commit conventions
  - Run `npm i ghooks punchcard-commit-msg --save-dev`
  - Add `config.ghooks.commit-msg` to `package.json` and set it to `punchcard-commit-msg`
- Set up [Semantic Release](https://github.com/semantic-release/semantic-release)
  - Follow general Semantic Release instructions
    - Using `Travis CI`
    - Do not create a `.travis.yml` file (that'll happen later)
  - Run `npm i punchcard-semantic-release --save-dev` to install Punchcard's Semantic Release configuration
    - Add `release.analyzeCommits` to `package.json and set it to `punchcard-semantic-release/analyze`
    - Add `release. generateNotes ` to `package.json and set it to `punchcard-semantic-release/notes `
- Set up testing and code coverage
  - Run `npm i ava tap-diff nyc coveralls eslint eslint-config-punchcard --save-dev`
  -  Add [ESLint Configuration](http://eslint.org/) files
    - `.eslintrc.yml` should [extend](http://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package) `punchcard`
    - `.eslintrc-ava.yml` should [extend](http://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package) `punchcard/configurations/ava`
  - Add NPM Scripts
    - Add `scripts.lint` to `package.json` and set it to `eslint index.js lib && eslint -c ./.eslintrc-ava.yml tests`
    - Add `scripts.ava` to `package.json` and set it to `ava | tap-diff`
    - Add `scripts.nyc` to `package.json` and set it to `nyc --all npm run ava`
    - Add `scripts.pretest` to `package.json` and set it to `npm run lint`
    - Add `scripts.test` to `package.json` and set it to `npm run nyc`
    - Add `scripts.coverage` to `package.json` and set it to `nyc report --reporter=text-lcov | coveralls`
  - Add testing configuration  
    - Add `nyc.exclude` to `package.json` and set it to `[ "tests/**/*" ]`
    - Add `ava.files` to `package.json` and set it to `[ "tests/**/*.js" ]`
    - Add `ava.failFast` to `package.json` and set it to `true`
    - Add `ava.tap` to `package.json` and set it to `true`
- Add `.travis.yml` file
  - Set `sudo` to `false`
  - Set `language` to `node_js`
  - Set `node_js` to `- '5.11'`
  - Set `cache.directories` to `- node_modules`
  - Set `before_script` to `- npm prune`
  - Set `after_success` to `- npm run coverage` and `- npm run semantic-release`
  - Set `branches.except` to `/^v\d+\.\d+\.\d+$/`
  - Set `notifications.email` to `false`
- Run `greenkeeper enable` to set up [Greenkeeper](https://greenkeeper.io/)
- Set up Travis for CI/CD
  - Go to [Travis](travis-ci.org) and enable Travis for the repository
  - Configure the [Travis Slack integration](https://slack.com/apps/A0F81FP4N-travis-ci) using the "Encrypting your credentials" setup instructions
  - Add relevant badges to README.md
- Set up Coveralls for Code Coverage
  - Go to [Coveralls](https://coveralls.io/) and enable Coveralls for the repository
  - Go to `/settings` for the repository in Coveralls
    - Disable `Leave Comments?`
    - Enable `Use Status API`
    - Ensure `Coverage Threshold for Failure` is blank
    - Set `Coverage Decrease Threshold for Failure` to `3`
    - Configure the [Incoming WebHooks integration](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) to add Slack for Coveralls (`/notifications/slack_webhook` from project homepage on Coveralls)
  - Add relevant badges to README.md
- Set up Node Security for continuous security monitoring
  - Go to [Node Security](https://nodesecurity.io/) and enable Node Security for the repository
  - Add relevant badges to README.md
- Set up GitHub Protected Branches
  - Travis and Coveralls will need to have run at least once before this step can be followed
  - Go to `/settings/branches` for the repository
  - Enable `Protected branches` for the `master` branch
    - Enable `Protect this branch`
    - Enable `Required status checks to pass before merging
    - Enable `Include administrators`
    - Enable  `Require branches to be up to date before merging`
    - Enable `continuous-integration/travis-ci` and `coverage/coveralls` for required checks

**Comment by Snugug** [comment]
And as a Wiki, so we can close:

https://github.com/punchcard-cms/punchcard/wiki/Setting-Up-a-New-Punchcard-Repository
